(function(ZR){'use strict';
 const SCOPES=new Set(['DIRECT','CONTEXTUAL','TRANSFERABLE','OUT_OF_SCOPE']);
 const STRENGTHS=new Set(['HIGH','MEDIUM','LOW']);
 function validate(p){if(!Number.isInteger(Number(p.paper_id))||Number(p.paper_id)<1||!String(p.scorecard_id||'').trim())throw new Error('paper and scorecard required');if(!SCOPES.has(p.corrected_scope)&&!(p.confirm_correct&&p.corrected_scope==='UNCERTAIN'))throw new Error('invalid corrected scope');if(['OUT_OF_SCOPE','UNCERTAIN'].includes(p.corrected_scope)){if(p.corrected_strength)throw new Error('this scope has no strength');}else if(!STRENGTHS.has(p.corrected_strength))throw new Error('invalid corrected strength');if(p.corrected_transferable_topic&&p.corrected_scope!=='TRANSFERABLE')throw new Error('transfer topic requires TRANSFERABLE');}
 async function add(p){validate(p);const latest=await ZR.DB.latestScreening(Number(p.paper_id),String(p.scorecard_id));if(!latest)throw new Error('screening not found');const mj=latest.model_judgement||ZR.Utils.safeJSON(latest.model_judgement_json,{});if(p.confirm_correct&&(p.corrected_scope!==(mj.scope||latest.scope)||p.corrected_strength!==(mj.strength||null)))throw new Error('confirmation must match model judgment');const id=await ZR.DB.addFeedback({paper_id:Number(p.paper_id),scorecard_id:String(p.scorecard_id),model_scope:mj.scope||latest.scope,model_strength:mj.strength||latest.strength,corrected_scope:p.corrected_scope,corrected_strength:p.corrected_strength||null,corrected_transferable_topic:p.corrected_transferable_topic||null,priority_feedback:p.priority_feedback||null,note:String(p.note||''),source:'USER_EXPLICIT',weight:1});let rebuilt=null,profileError=null;try{rebuilt=await ZR.Feedback.maybeRebuild(String(p.scorecard_id))}catch(e){profileError=String(e);try{Zotero.logError(e)}catch(_){}}await ZR.Screening.rescorePaper(Number(p.paper_id),String(p.scorecard_id));try{await ZR.DB.loadItemCache();ZR.UI?.refreshColumns?.()}catch(_){}ZR.Events?.emit('feedback:changed',{paperID:Number(p.paper_id),scorecardID:String(p.scorecard_id)});return{id,rebuilt,profileError};}
 async function revoke(id){const f=await ZR.DB.row('SELECT id,paper_id,scorecard_id FROM feedback WHERE id=?',[Number(id)]);if(!f)throw new Error('feedback not found');const ok=await ZR.DB.revokeFeedback(Number(id));if(!ok)return false;try{await ZR.Feedback.rebuild(String(f.scorecard_id))}catch(e){try{Zotero.logError(e)}catch(_){}}await ZR.Screening.rescoreScorecard(String(f.scorecard_id));try{await ZR.DB.loadItemCache();ZR.UI?.refreshColumns?.()}catch(_){}ZR.Events?.emit('feedback:changed',{paperID:Number(f.paper_id),scorecardID:String(f.scorecard_id)});return true;}
 async function recent(scorecardID,limit=100){return ZR.DB.pickRows(await ZR.DB.all('SELECT f.*,p.title AS paper_title FROM feedback f LEFT JOIN papers p ON p.id=f.paper_id WHERE f.scorecard_id=? ORDER BY f.id DESC LIMIT ?',[String(scorecardID),Math.min(100,Math.max(1,Number(limit)||100))]),['id','paper_id','paper_title','scorecard_id','model_scope','model_strength','corrected_scope','corrected_strength','corrected_transferable_topic','priority_feedback','note','active','source','weight','created_at','updated_at','supersedes_feedback_id']);}
 async function status(scorecardID){const p=await ZR.DB.profileStatus(String(scorecardID));return {...p,maturityCap:ZR.Feedback.maturityCap(Number(p.counts?.total||0))};}
 async function rebuild(scorecardID){const p=await ZR.Feedback.rebuild(String(scorecardID));await ZR.Screening.rescoreScorecard(String(scorecardID));try{await ZR.DB.loadItemCache();ZR.UI?.refreshColumns?.();}catch(_){}ZR.Events?.emit('feedback:changed',{scorecardID:String(scorecardID)});return p;}
 async function rollback(scorecardID,version){if(!(await ZR.DB.rollbackProfile(String(scorecardID),Number(version))))throw new Error('profile version not found');await ZR.Screening.rescoreScorecard(String(scorecardID));try{await ZR.DB.loadItemCache();ZR.UI?.refreshColumns?.();}catch(_){}ZR.Events?.emit('feedback:changed',{scorecardID:String(scorecardID)});return true;}
 ZR.Services=ZR.Services||{};ZR.Services.Feedback={add,revoke,recent,status,rebuild,rollback,validate};
})(ZR);
