(function(ZR){'use strict';
  function rows(){return (ZR.Config.subscriptions.subscriptions||[]).map(x=>JSON.parse(JSON.stringify(x)));}
  function validate(x,existingID=null){if(!x||typeof x!=='object')throw new Error('Subscription required');const id=String(x.id||'').trim();if(!/^[A-Za-z0-9_-]+$/.test(id))throw new Error('Invalid subscription ID');if(!String(x.label||'').trim())throw new Error('Subscription label required');if(!ZR.Scorecards.has(String(x.scorecard||'')))throw new Error('Unknown or disabled Scorecard: '+x.scorecard);if(!Array.isArray(x.feed_ids))throw new Error('feed_ids must be an array');const feedIDs=new Set((ZR.Config.feeds.feeds||[]).map(f=>String(f.id)));for(const f of x.feed_ids)if(!feedIDs.has(String(f)))throw new Error('Unknown feed: '+f);if(!existingID&&rows().some(r=>r.id===id))throw new Error('Subscription ID already exists');return {...x,id,label:String(x.label).trim(),scorecard:String(x.scorecard),feed_ids:[...new Set(x.feed_ids.map(String))],enabled:x.enabled!==false,default:!!x.default};}
  async function persist(list){if(list.filter(x=>x.enabled!==false).length<1)throw new Error('At least one enabled subscription is required');if(!list.some(x=>x.default&&x.enabled!==false)){const a=list.find(x=>x.enabled!==false);if(a)a.default=true;}let seen=false;for(const x of list){if(x.default&&x.enabled!==false){if(seen)x.default=false;else seen=true;}}await ZR.ConfigManager.saveSubscriptions({...ZR.Config.subscriptions,subscriptions:list});const cur=String(ZR.Utils.getPref('defaultSubscription','')||'');if(!list.some(x=>x.id===cur&&x.enabled!==false)){const d=list.find(x=>x.default&&x.enabled!==false)||list.find(x=>x.enabled!==false);if(d)ZR.Utils.setPref('defaultSubscription',d.id);}try{await ZR.DB.loadItemCache();ZR.UI?.refreshColumns?.();}catch(_){}ZR.Events?.emit('subscriptions:changed',{subscriptions:list});return list;}
  async function list(){return rows();}
  async function get(id){const x=rows().find(r=>r.id===String(id));if(!x)throw new Error('Unknown subscription: '+id);return x;}
  async function create(x){const v=validate(x);return persist([...rows(),v]).then(()=>v);}
  async function update(id,x){const list=rows(),i=list.findIndex(r=>r.id===String(id));if(i<0)throw new Error('Unknown subscription: '+id);const v=validate({...list[i],...x,id:String(id)},String(id));list[i]=v;await persist(list);return v;}
  async function remove(id){const list=rows(),i=list.findIndex(r=>r.id===String(id));if(i<0)throw new Error('Unknown subscription: '+id);if(list.length<=1)throw new Error('Cannot remove the last subscription');const [old]=list.splice(i,1);await persist(list);return old;}
  async function duplicate(id,newID,newLabel){const src=await get(id);return create({...src,id:newID,label:newLabel||src.label+' Copy',default:false});}
  async function run(id){return ZR.Screening.runFeeds(String(id));}
  async function defaultSubscription(){const list=rows();const preferred=String(ZR.Utils.getPref('defaultSubscription','')||'');return list.find(x=>x.id===preferred&&x.enabled!==false)||list.find(x=>x.default&&x.enabled!==false)||list.find(x=>x.enabled!==false)||null;}
  async function setDefault(id){const sub=await get(id);if(sub.enabled===false)throw new Error('Subscription is disabled: '+id);ZR.Utils.setPref('defaultSubscription',sub.id);ZR.Utils.setPref('dashboardSubscription',sub.id);try{await ZR.DB.loadItemCache();ZR.UI?.refreshColumns?.();}catch(_){}ZR.Events?.emit('subscriptions:default-changed',{subscriptionID:sub.id});return sub;}
  async function counts(){const out={};for(const s of rows()){try{out[s.id]=Number(await ZR.DB.value('SELECT COUNT(DISTINCT paper_id) FROM screenings WHERE subscription_id=?',[s.id])||0);}catch(_){out[s.id]=0;}}return out;}
  ZR.Services=ZR.Services||{};ZR.Services.Subscriptions={list,get,create,update,remove,duplicate,run,validate,counts,defaultSubscription,setDefault};
})(ZR);
