(() => {
'use strict';
const CTX=(window.arguments&&window.arguments[0]&&window.arguments[0].wrappedJSObject)||window.arguments?.[0]||{};
const ZR=CTX.ZR||window.opener?.Zotero?.ZotRadar;
const Zotero=CTX.Zotero||window.opener?.Zotero;
const S={page:'papers',subscriptionID:null,selectedPaperID:null,papersRenderToken:0,searchComposing:false,filters:{grade:'',scope:'',topic:'',priorityAuthorsOnly:false,read:'unread',imported:'all',search:'',sort:'priority'},multiSelect:false,selectedPaperIDs:new Set(),selectedPaperTitles:new Map(),visiblePaperIDs:[],unsubs:[],editSubscriptionID:null,editFeedID:null,editScorecardID:null,scorecardDraft:null,scorecardJSON:false};
const q=id=>document.getElementById(id);
const html=tag=>document.createElementNS('http://www.w3.org/1999/xhtml',tag);
async function ensureDashboardStyles(){
  const header=document.querySelector('.zr-header');
  if(header&&window.getComputedStyle(header).display==='flex')return;
  // Some Zotero/XUL installations do not apply an XML stylesheet processing
  // instruction from a packaged window. Load the same bundled CSS explicitly.
  const css=await ZR.Utils.readResourceText('content/ui/dashboard/dashboard.css');
  const style=html('style');style.id='zr-dashboard-inline-styles';style.textContent=css;
  document.documentElement.appendChild(style);
  if(window.getComputedStyle(header).display!=='flex')throw new Error('ZotRadar dashboard stylesheet did not apply');
}
const t=(key,vars={})=>ZR?.I18n?.t(key,vars)||key;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));
function toast(msg,bad=false,sticky=false){const el=q('zr-toast');el.textContent=msg;el.hidden=false;el.classList.toggle('zr-danger',!!bad);clearTimeout(toast._timer);if(!sticky)toast._timer=setTimeout(()=>{el.hidden=true},6000)}
function feedRunMessage(result,key='native.runDone'){const summary=t(key,{fetched:result.fetched||0,screenings:result.screenings||0,errors:result.errors||0});const failure=result.feed_errors?.[0];return failure?summary+' '+t('native.feedErrorDetails',{id:failure.id,message:failure.message}):summary}
function action(label,fn,cls=''){const b=html('button');b.textContent=label;if(cls)b.className=cls;b.addEventListener('click',async e=>{e.stopPropagation();if(b.disabled)return;b.disabled=true;b.setAttribute('aria-busy','true');try{await fn(e)}catch(err){toast(ZR.I18n.error(err),true);try{Zotero?.logError?.(err)}catch(_){}}finally{b.disabled=false;b.removeAttribute('aria-busy')}});return b}
function input(value='',type='text'){const el=html('input');el.type=type;el.value=value??'';return el}
function textarea(value='',rows=3){const el=html('textarea');el.rows=rows;el.value=value??'';return el}
function checkbox(value=false){const el=html('input');el.type='checkbox';el.checked=!!value;return el}
function field(label,control,hint=''){const row=html('label');row.className='zr-field';const cap=html('span');cap.className='zr-field-label';cap.textContent=label;row.append(cap,control);if(hint){const h=html('small');h.className='zr-muted';h.textContent=hint;row.appendChild(h)}return row}
function enabledSubscriptions(rows){return rows.filter(x=>x.enabled!==false)}
function lines(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function linesText(v){return (v||[]).join('\n')}
function openExternal(url){if(typeof Zotero?.launchURL==='function')Zotero.launchURL(url);else window.open(url,'_blank','noopener')}
function linkedText(text,url,cls=''){const a=html('a');a.className='zr-external-link '+cls;a.href=url;a.textContent=String(text||'');a.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openExternal(url)});return a}
function doiURL(doi){return 'https://doi.org/'+String(doi||'').trim().split('/').map(x=>encodeURIComponent(x)).join('/')}
function titleURL(p){return ZR.Settings.get('titleLinkTarget')==='doi'&&p.doi?doiURL(p.doi):'https://pubmed.ncbi.nlm.nih.gov/?term='+encodeURIComponent(p.title||'')}
function authorName(a){return typeof a==='string'?a:String(a?.name||a?.fullName||[a?.firstName,a?.lastName].filter(Boolean).join(' ')||'')}
function compactAuthors(authors){const all=(authors||[]).map(authorName).filter(Boolean);return all.length<=4?all:[...all.slice(0,2),'…',...all.slice(-2)]}
function isPriorityAuthor(author){return ZR.Services.Papers.priorityAuthorMatches(author,ZR.Settings.get('priorityAuthors'))}
function shortTier(value){const found=String(value||'').match(/([1-4一二三四])\s*区/);if(!found)return'—';return({'一':'1','二':'2','三':'3','四':'4'}[found[1]]||found[1])+'区'}
function journalMarkup(p){const name=p.journal||(p.preprint_source==='Preprint'?'':p.preprint_source)||'—';if(p.is_preprint)return `<div class="zr-journal-name">${esc(name)}</div><div class="zr-journal-metrics"><span class="zr-preprint-tag">${esc(t('native.preprint'))}</span></div>`;const m=p.journal_metric||{},value=m.impact_factor==null?null:Number(m.impact_factor),impact=value!=null&&Number.isFinite(value)?value.toFixed(1):'—',tier=shortTier(m.cas_tier),ifBand=value==null||!Number.isFinite(value)?'none':value>=10?'top':value>=5?'high':value>=2?'mid':'low',tierBand=tier==='—'?'none':'t'+tier[0];return `<div class="zr-journal-name">${esc(name)}</div><div class="zr-journal-metrics"><span class="zr-metric-if" data-band="${ifBand}">IF ${esc(impact)}</span><span class="zr-metric-tier" data-band="${tierBand}">${esc(tier)}</span></div>`}
function paperColumns(){const cols=['grade','score','paper','journal'];if(ZR.Settings.get('showScopeColumn')!==false)cols.push('scope');if(ZR.Settings.get('showTopicColumn')===true)cols.push('topic');cols.push('date');return cols}
function topicLabels(scorecard){const map=new Map();for(const topic of [...(scorecard.topics||[]),...(scorecard.scope?.transferable?.topics||[])])if(topic?.id)map.set(String(topic.id),String(topic.label||topic.id));return map}
function topicValues(p){return [...new Set([...(p.topics||[]),p.transferable_topic].filter(Boolean).map(String))]}
function markPapersFilterPending(){const root=q('zr-page-papers');root?.setAttribute('aria-busy','true');root?.classList.add('zr-filter-pending');const summary=root?.querySelector('.zr-grade-summary');if(summary)summary.textContent=t('native.filtering')}
function scopeLabel(value){switch(value){case'DIRECT':return t('native.scope.DIRECT');case'CONTEXTUAL':return t('native.scope.CONTEXTUAL');case'TRANSFERABLE':return t('native.scope.TRANSFERABLE');case'OUT_OF_SCOPE':return t('native.scope.OUT_OF_SCOPE');default:return t('native.scope.UNCERTAIN')}}
function strengthLabel(value){switch(value){case'HIGH':return t('native.strength.HIGH');case'LOW':return t('native.strength.LOW');default:return t('native.strength.MEDIUM')}}
async function resolveSubscription(){const all=await ZR.Services.Subscriptions.list(),rows=enabledSubscriptions(all);const preferred=S.subscriptionID||ZR.Utils.getPref('dashboardSubscription','')||ZR.Settings.get('defaultSubscription');const disabled=all.find(x=>x.id===preferred&&x.enabled===false)||null;if(disabled)return{rows,sub:null,disabled};if(!rows.length)return{rows,sub:null,disabled:null};const sub=rows.find(x=>x.id===preferred)||rows[0];S.subscriptionID=sub.id;return{rows,sub,disabled:null}}
async function navigate(page,opts={}){S.page=page||'papers';if(opts.subscriptionID)S.subscriptionID=String(opts.subscriptionID);if(opts.paperID)S.selectedPaperID=Number(opts.paperID);ZR.Utils.setPref('dashboardPage',S.page);document.querySelectorAll('#zr-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===S.page));document.querySelectorAll('.zr-page').forEach(p=>p.classList.toggle('active',p.id===`zr-page-${S.page}`));await renderCurrent()}
async function renderCurrent(){if(S.page==='papers')return renderPapers();if(S.page==='subscriptions')return renderSubscriptions();if(S.page==='scorecards')return renderScorecards();if(S.page==='feedback')return renderFeedback();if(S.page==='system')return renderSystem()}

async function renderPapers(){
  const token=++S.papersRenderToken;
  const root=q('zr-page-papers');if(!root.firstElementChild)root.innerHTML=`<div class="zr-empty">${esc(t('common.loading'))}</div>`;
  const {rows:subs,sub,disabled}=await resolveSubscription();if(token!==S.papersRenderToken)return;
  if(!sub){const box=html('div');box.className='zr-empty';box.textContent=disabled?t('native.disabledSubscriptionHidden',{subscription:disabled.label}):t('native.noSubscriptions');if(subs.length){const picker=selectFilter([['',t('native.chooseSubscription')],...subs.map(s=>[s.id,s.label])],'',async id=>{if(!id)return;S.subscriptionID=id;await ZR.Services.Subscriptions.setDefault(id);await renderPapers()});picker.setAttribute('aria-label',t('native.subscriptionDirection'));box.appendChild(picker)}root.replaceChildren(box);return}
  const scorecard=(await ZR.Services.Scorecards.get(sub.scorecard)).card;
  if(token!==S.papersRenderToken)return;
  const columns=paperColumns(),topicNames=topicLabels(scorecard);
  if(!columns.includes('scope'))S.filters.scope='';
  if(!columns.includes('topic'))S.filters.topic='';
  const content=document.createDocumentFragment();
  const toolbar=html('div');toolbar.className='zr-toolbar';
  const subSel=html('select');for(const s of subs){const o=html('option');o.value=s.id;o.textContent=s.label;o.selected=s.id===sub.id;subSel.appendChild(o)}
  subSel.setAttribute('aria-label',t('native.subscriptionDirection'));
  subSel.addEventListener('change',()=>{S.subscriptionID=subSel.value;S.selectedPaperID=null;S.selectedPaperIDs.clear();S.selectedPaperTitles.clear();ZR.Services.Subscriptions.setDefault(subSel.value).then(()=>renderPapers()).catch(showDashboardError)});toolbar.appendChild(subSel);
  const search=input(S.filters.search,'search');search.placeholder=t('native.searchPlaceholder');const queueSearch=()=>{S.filters.search=search.value;clearTimeout(renderPapers._searchTimer);renderPapers._searchTimer=setTimeout(()=>renderPapers().catch(showDashboardError),180)};search.addEventListener('compositionstart',()=>{S.searchComposing=true});search.addEventListener('compositionend',()=>{S.searchComposing=false;queueSearch()});search.addEventListener('input',()=>{S.filters.search=search.value;if(!S.searchComposing)queueSearch()});toolbar.appendChild(search);
  const readGroup=html('div');readGroup.className='zr-read-filter';for(const [value,key] of [['unread','native.unread'],['read','native.read'],['all','native.all']]){const b=action(t(key),async()=>{if(S.filters.read===value)return;S.filters.read=value;for(const button of readGroup.querySelectorAll('button')){const active=button===b;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))}markPapersFilterPending();await renderPapers()});b.classList.toggle('active',S.filters.read===value);b.setAttribute('aria-pressed',String(S.filters.read===value));readGroup.appendChild(b)}toolbar.appendChild(readGroup);
  const imported=selectFilter([['all',t('native.fetchedAll')],['imported',t('native.imported')],['unimported',t('native.unimported')]],S.filters.imported,async value=>{if(S.filters.imported===value)return;S.filters.imported=value;markPapersFilterPending();await renderPapers()});imported.className='zr-import-filter';imported.setAttribute('aria-label',t('native.importStatus'));toolbar.appendChild(imported);
  const multi=action(S.multiSelect?t('native.closeMultiSelect'):t('native.multiSelect'),async()=>{S.multiSelect=!S.multiSelect;await renderPapers()},'zr-multi-toggle');multi.setAttribute('aria-pressed',String(S.multiSelect));toolbar.appendChild(multi);
  toolbar.appendChild(action(t('native.runCurrent'),async()=>{toast(t('native.running'));const r=await ZR.Services.Subscriptions.run(sub.id);toast(feedRunMessage(r),!!r.errors,!!r.errors);await renderPapers()},'zr-run-current'));content.appendChild(toolbar);
  const result=await ZR.Services.Papers.list({subscriptionID:sub.id,...S.filters,all:true});
  if(token!==S.papersRenderToken)return;
  const counts=result.grade_counts||result.rows.reduce((acc,p)=>{const grade=String(p.grade||'').toUpperCase();acc[Object.hasOwn(acc,grade)&&grade!=='other'?grade:'other']++;return acc},{A:0,B:0,C:0,D:0,other:0});
  const info=html('div');info.className='zr-grade-summary';info.textContent=t('native.papersGradeSummary',{A:counts.A,B:counts.B,C:counts.C,D:counts.D,other:counts.other,total:result.total});content.appendChild(info);
  const wrap=html('div');wrap.className='zr-table-wrap';const table=html('table');table.className='zr-paper-table';table.style.minWidth=(columns.length+(S.multiSelect?1:0)>=8?'1180px':columns.length>=7?'1040px':'900px');table.classList.toggle('zr-selecting',S.multiSelect);const colgroup=html('colgroup');const widths={grade:6,score:8,paper:40+(columns.includes('scope')?0:12)-(columns.includes('topic')?12:0)-(S.multiSelect?4:0),journal:25,scope:12,topic:12,date:9,select:4};for(const key of S.multiSelect?['select',...columns]:columns){const col=html('col');col.style.width=widths[key]+'%';colgroup.appendChild(col)}table.appendChild(colgroup);const head=html('thead');head.className='zr-list-head';const headRow=html('tr');
  if(S.multiSelect){const cell=html('th');cell.scope='col';cell.textContent=t('native.select');headRow.appendChild(cell)}
  for(const column of columns){const key={grade:'native.colGrade',score:'native.colScore',paper:'native.colPaper',journal:'native.colJournal',scope:'native.colScope',topic:'native.colTopics',date:'native.colDate'}[column];
    const cell=html('th');cell.scope='col';cell.className='zr-col-'+column;
    if(key==='native.colGrade')cell.appendChild(headerFilter(t(key),[['',''],...['A','B','C','D'].map(x=>[x,x]),['UNRATED','—']],S.filters.grade,v=>{S.filters.grade=v;return renderPapers()}));
    else if(key==='native.colScope')cell.appendChild(headerFilter(t(key),[['',''],...['DIRECT','CONTEXTUAL','TRANSFERABLE','OUT_OF_SCOPE','UNCERTAIN'].map(x=>[x,scopeLabel(x)])],S.filters.scope,v=>{S.filters.scope=v;return renderPapers()}));
    else if(key==='native.colTopics')cell.appendChild(headerFilter(t(key),[['',''],...[...topicNames].map(([id,label])=>[id,label])],S.filters.topic,v=>{S.filters.topic=v;return renderPapers()}));
    else if(key==='native.colScore')cell.appendChild(sortHeader(t(key),'score_desc',t('native.sortScoreDesc')));
    else if(key==='native.colJournal')cell.appendChild(sortHeader(t(key),'if_desc',t('native.sortIFDesc')));
    else if(key==='native.colDate')cell.appendChild(sortHeader(t(key),'date_desc',t('native.sortDateDesc')));
    else if(key==='native.colPaper'){const toggle=action(t(key),async()=>{S.filters.priorityAuthorsOnly=!S.filters.priorityAuthorsOnly;await renderPapers()},'zr-head-toggle zr-author-toggle');toggle.title=t('native.filterPriorityAuthors');toggle.classList.toggle('active',S.filters.priorityAuthorsOnly);toggle.setAttribute('aria-pressed',String(S.filters.priorityAuthorsOnly));cell.appendChild(toggle)}
    else cell.textContent=t(key);
    headRow.appendChild(cell);
  }
  head.appendChild(headRow);table.appendChild(head);wrap.appendChild(table);content.appendChild(wrap);
  if(!result.rows.length){const empty=html('div');empty.className='zr-empty';empty.textContent=t('native.emptyPapers');content.appendChild(empty)}
  for(const p of result.rows){table.appendChild(await renderPaperCard(p,sub,columns,topicNames));if(token!==S.papersRenderToken)return}
  if(S.multiSelect)content.appendChild(renderBulkBar());
  if(token===S.papersRenderToken){const focusedSearch=root.querySelector('.zr-toolbar input[type=search]'),restoreFocus=document.activeElement===focusedSearch,selection=restoreFocus?[focusedSearch.selectionStart,focusedSearch.selectionEnd]:null;if(S.searchComposing||search.value!==S.filters.search)return;S.visiblePaperIDs=result.rows.map(p=>p.paper_id);for(const p of result.rows)S.selectedPaperTitles.set(p.paper_id,p.title);root.classList.toggle('zr-multi-active',S.multiSelect);root.replaceChildren(content);root.classList.remove('zr-filter-pending');root.removeAttribute('aria-busy');if(restoreFocus){search.focus({preventScroll:true});try{search.setSelectionRange(...selection)}catch(_){}}ZR.Services.Papers.queueJournalMetrics?.(result.rows);ZR.Services.Papers.queueTitleTranslations?.(result.rows,{priority:true})}
}
function headerFilter(label,options,current,onChange){const el=html('select');el.className='zr-head-filter';el.setAttribute('aria-label',label);for(const [value,text] of options){const o=html('option');o.value=value;o.textContent=value?`${label} · ${text}`:label;o.selected=value===current;el.appendChild(o)}el.addEventListener('change',()=>{try{Promise.resolve(onChange(el.value)).catch(showDashboardError)}catch(e){showDashboardError(e)}});return el}
function sortHeader(label,key,hint){const button=action(label,async()=>{S.filters.sort=S.filters.sort===key?'priority':key;await renderPapers()},'zr-head-toggle');button.title=hint;button.classList.toggle('active',S.filters.sort===key);button.setAttribute('aria-pressed',String(S.filters.sort===key));return button}
function selectFilter(options,current,onChange){const el=html('select');for(const [value,label] of options){const o=html('option');o.value=value;o.textContent=label;o.selected=value===current;el.appendChild(o)}el.addEventListener('change',()=>{try{Promise.resolve(onChange(el.value)).catch(showDashboardError)}catch(e){showDashboardError(e)}});return el}
function updateBulkSelectionUI(){const root=q('zr-page-papers');for(const box of root.querySelectorAll('.zr-row-select'))box.checked=S.selectedPaperIDs.has(Number(box.value));const count=root.querySelector('.zr-bulk-count');if(count)count.textContent=t('native.selectedCount',{count:S.selectedPaperIDs.size})}
async function copySelectedTitles(){const titles=[...S.selectedPaperIDs].map(id=>S.selectedPaperTitles.get(id)).filter(Boolean);if(!titles.length)return toast(t('native.selectPapers'),true);const value=titles.join('\n');if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(value);else Components.classes['@mozilla.org/widget/clipboardhelper;1'].getService(Components.interfaces.nsIClipboardHelper).copyString(value);toast(t('native.copiedTitles',{count:titles.length}))}
function renderBulkBar(){
  const bar=html('div');bar.className='zr-bulkbar';const count=html('span');count.className='zr-bulk-count';count.textContent=t('native.selectedCount',{count:S.selectedPaperIDs.size});bar.appendChild(count);
  bar.append(action(t('native.selectPage'),()=>{for(const id of S.visiblePaperIDs)S.selectedPaperIDs.add(id);updateBulkSelectionUI()}),action(t('native.invertSelection'),()=>{for(const id of S.visiblePaperIDs){if(S.selectedPaperIDs.has(id))S.selectedPaperIDs.delete(id);else S.selectedPaperIDs.add(id)}updateBulkSelectionUI()}),action(t('native.clearSelection'),()=>{S.selectedPaperIDs.clear();updateBulkSelectionUI()}),action(t('native.copyTitles'),copySelectedTitles),action(t('native.importZotero'),async()=>{if(!S.selectedPaperIDs.size)return toast(t('native.selectPapers'),true);const result=await ZR.Services.Papers.importMany([...S.selectedPaperIDs]);toast(t('native.bulkImported',result));await renderPapers()}),action(t('native.rescreenBulk'),async()=>{if(!S.selectedPaperIDs.size)return toast(t('native.selectPapers'),true);toast(t('native.rescreening'),false,true);const result=await ZR.Services.Papers.rescreenMany([...S.selectedPaperIDs],S.subscriptionID);const detail=result.error?' · '+ZR.I18n.error(result.error):'';toast(t('native.bulkRescreened',result)+detail,result.failed>0||result.unscored>0);await renderPapers()}),action(t('native.markReadBulk'),async()=>{if(!S.selectedPaperIDs.size)return toast(t('native.selectPapers'),true);const ids=[...S.selectedPaperIDs];await ZR.Services.Papers.setReadStates(ids,true);S.selectedPaperIDs.clear();toast(t('native.bulkRead',{count:ids.length}));await renderPapers()}),action(t('native.markUnreadBulk'),async()=>{if(!S.selectedPaperIDs.size)return toast(t('native.selectPapers'),true);const ids=[...S.selectedPaperIDs];await ZR.Services.Papers.setReadStates(ids,false);S.selectedPaperIDs.clear();toast(t('native.bulkUnread',{count:ids.length}));await renderPapers()}));return bar;
}
async function renderPaperCard(p,sub,columns,topicNames){
  const card=html('tbody');card.className='zr-card';card.dataset.paperId=String(p.paper_id);
  card.dataset.journalKey=ZR.Journal.normalizeJournal(p.journal);
  const row=html('tr');row.className='zr-row';
  row.classList.toggle('zr-is-read',!!p.read);
  const score=Math.max(0,Math.min(100,Number(p.reading_priority||0)));
  row.innerHTML=`<td class="zr-grade" data-grade="${esc(p.grade||'')}"><span class="zr-grade-letter">${esc(p.grade||'—')}</span></td><td class="zr-score"><b>${p.reading_priority==null?'—':Number(p.reading_priority).toFixed(1)}</b><div class="zr-progress" role="progressbar" aria-valuenow="${score}" aria-valuemin="0" aria-valuemax="100"><span style="width:${score}%"></span></div></td><td class="zr-paper-info"><div class="zr-title"></div><div class="zr-title-zh"></div><div class="zr-author-line"></div></td><td class="zr-journal">${journalMarkup(p)}</td>${columns.includes('scope')?`<td class="zr-scope" data-scope="${esc(p.scope||'')}">${esc(scopeLabel(p.scope||'UNCERTAIN'))}</td>`:''}${columns.includes('topic')?`<td class="zr-topics">${esc(topicValues(p).map(id=>topicNames.get(id)||id).join(', ')||'—')}</td>`:''}<td class="zr-date">${esc(p.published||'')}</td>`;
  if(S.multiSelect){const cell=html('td');cell.className='zr-select-cell';const box=checkbox(S.selectedPaperIDs.has(p.paper_id));box.className='zr-row-select';box.value=String(p.paper_id);box.setAttribute('aria-label',t('native.selectPaper',{title:p.title}));box.addEventListener('click',e=>e.stopPropagation());box.addEventListener('change',e=>{e.stopPropagation();if(box.checked)S.selectedPaperIDs.add(p.paper_id);else S.selectedPaperIDs.delete(p.paper_id);updateBulkSelectionUI()});cell.appendChild(box);row.prepend(cell)}
  row.querySelector('.zr-title').appendChild(linkedText(p.title,titleURL(p)));
  if(p.read){const tag=html('span');tag.className='zr-read-tag';tag.textContent=t('native.read');row.querySelector('.zr-title').appendChild(tag)}
  const zh=row.querySelector('.zr-title-zh');if(ZR.Settings.get('showChineseTitle'))zh.textContent=p.title_zh||t('native.translationPending');else zh.hidden=true;
  const authors=row.querySelector('.zr-author-line');let authorIndex=0;for(const name of compactAuthors(p.authors)){if(authorIndex++)authors.appendChild(document.createTextNode(', '));if(name==='…'){const gap=html('span');gap.textContent='…';authors.appendChild(gap);continue}const link=linkedText(name,'https://scholar.google.com/scholar?q='+encodeURIComponent(name),'zr-author-link');if(isPriorityAuthor(name))link.classList.add('zr-priority-author');authors.appendChild(link)}
  row.addEventListener('click',()=>{
    try{
      if(S.selectedPaperID===p.paper_id){S.selectedPaperID=null;card.querySelector('.zr-detail-row')?.remove();return}
      q('zr-page-papers').querySelectorAll('.zr-detail-row').forEach(el=>el.remove());
      S.selectedPaperID=p.paper_id;card.appendChild(detailRow(p,sub,columns));
    }catch(error){showDashboardError(error)}
  });
  card.appendChild(row);
  if(S.selectedPaperID===p.paper_id)card.appendChild(detailRow(p,sub,columns));
  return card;
}
function detailRow(p,sub,columns){const row=html('tr');row.className='zr-detail-row';const cell=html('td');cell.colSpan=columns.length+(S.multiSelect?1:0);cell.appendChild(renderPaperDetail(p,sub));row.appendChild(cell);return row}
function renderPaperDetail(p,sub){
  const d=html('div');d.className='zr-detail';
  const scored=p.reading_priority!=null,feedbackValue=scored?Number(p.feedback_adjustment||0).toFixed(1):'—',journalValue=scored?Number(p.journal_adjustment||0).toFixed(1):'—';
  const feedbackNote=scored?(p.user_overridden?t('native.manualFeedbackApplied'):t('native.noFeedbackApplied')):t('native.notYetScored');
  const journalNote=t('native.journalScoreValue',{score:p.journal_score==null?'—':Number(p.journal_score).toFixed(1)})+(scored&&Number(p.journal_adjustment||0)===0?' · '+t('native.noJournalChange'):'');
  d.innerHTML=`${scored?'':`<p class="zr-warning">${esc(t('native.unscoredHint'))}</p>`}<p><b>${esc(t('native.reason'))}:</b> ${esc(p.reason||'—')}</p>
    <p><b>${esc(t('native.abstract'))}:</b> ${esc(p.abstract||t('native.noAbstract'))}</p>
    <p class="zr-doi-line"><b>DOI:</b> <span class="zr-doi-target"></span></p>
    <div class="zr-score-grid">
      <div><b>${esc(t('native.baseRelevance'))}</b><br/>${esc(p.base_relevance??'—')}</div>
      <div><b>${esc(t('native.feedbackAdj'))}</b><br/>${esc(feedbackValue)}<small class="zr-muted">${esc(feedbackNote)}</small></div>
      <div><b>${esc(t('native.journalAdj'))}</b><br/>${esc(journalValue)}<small class="zr-muted">${esc(journalNote)}</small></div>
      <div><b>${esc(t('native.personalized'))}</b><br/>${esc(p.personalized_relevance??'—')}</div>
      <div><b>${esc(t('native.priority'))}</b><br/>${esc(p.reading_priority??'—')}</div>
    </div>${renderEvidence(p)}`;
  const doi=d.querySelector('.zr-doi-target');if(p.doi)doi.appendChild(linkedText(p.doi,doiURL(p.doi)));else d.querySelector('.zr-doi-line').hidden=true;
  const actions=html('div');actions.className='zr-actions';
  actions.append(action(t('native.rescreen'),async()=>{toast(t('native.rescreening'),false,true);const result=await ZR.Services.Papers.rescreen(p.paper_id,sub.id);toast(t(result?.scores?.reading_priority==null?'native.rescreenUnscored':'native.rescreened'),result?.scores?.reading_priority==null);await renderPapers()}),action(p.zotero_key?t('native.inZotero'):t('native.importZotero'),async()=>{if(!p.zotero_key){await ZR.Services.Papers.importToZotero(p.paper_id);toast(t('native.imported'));await renderPapers()}}),action(p.read?t('native.markUnread'):t('native.markRead'),async()=>{await ZR.Services.Papers.setReadStates([p.paper_id],!p.read);toast(p.read?t('native.markedUnread'):t('native.markedRead'));await renderPapers()}));
  d.appendChild(actions);d.appendChild(feedbackEditor(p));return d;
}
function renderEvidence(p){const pos=(p.positive_evidence||[]),neg=(p.negative_evidence||[]);if(!pos.length&&!neg.length&&!p.uncertainty)return'';return `<div class="zr-evidence"><div><b>${esc(t('native.positiveEvidence'))}</b><ul>${pos.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>—</li>'}</ul></div><div><b>${esc(t('native.negativeEvidence'))}</b><ul>${neg.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>—</li>'}</ul></div></div>${p.uncertainty?`<p><b>${esc(t('native.uncertainty'))}:</b> ${esc(p.uncertainty)}</p>`:''}`}

async function renderSubscriptions(){
  const root=q('zr-page-subscriptions');root.innerHTML=`<div class="zr-empty">${esc(t('common.loading'))}</div>`;
  const [subs,feeds,cards,counts]=await Promise.all([ZR.Services.Subscriptions.list(),ZR.Services.Feeds.list(),ZR.Services.Scorecards.list({includeDisabled:false}),ZR.Services.Subscriptions.counts()]);root.textContent='';
  const head=html('div');head.className='zr-page-head';head.innerHTML=`<div><h2>${esc(t('native.subscriptionsTitle'))}</h2><p class="zr-muted">${esc(t('native.subscriptionsDesc'))}</p></div>`;head.appendChild(action(t('native.newSubscription'),async()=>{S.editSubscriptionID='__new__';await renderSubscriptions()}));root.appendChild(head);
  const layout=html('div');layout.className='zr-manager-grid';const list=html('div');list.className='zr-manager-list';const editor=html('div');editor.className='zr-manager-editor';layout.append(list,editor);root.appendChild(layout);
  for(const sub of subs){const item=html('div');item.className='zr-manager-item'+(S.editSubscriptionID===sub.id?' selected':'');const cardMeta=cards.find(c=>c.id===sub.scorecard);item.innerHTML=`<div><b>${esc(sub.label)}</b>${sub.default?` <span class="zr-badge">${esc(t('native.default'))}</span>`:''}${sub.enabled===false?` <span class="zr-badge">${esc(t('native.disabled'))}</span>`:''}</div><small>${esc(sub.id)} · ${esc(cardMeta?.label||sub.scorecard)} · ${sub.feed_ids?.length||0} ${esc(t('native.feeds'))} · ${counts[sub.id]||0} ${esc(t('native.papers'))}</small>`;
    const acts=html('div');acts.className='zr-inline-actions';acts.append(action(t('common.edit'),async()=>{S.editSubscriptionID=sub.id;await renderSubscriptions()}),action(t('native.runCurrent'),async()=>{const r=await ZR.Services.Subscriptions.run(sub.id);toast(feedRunMessage(r),!!r.errors,!!r.errors);await renderSubscriptions()}),action(t('native.setDefault'),async()=>{await ZR.Services.Subscriptions.setDefault(sub.id);toast(t('native.defaultUpdated'));await renderSubscriptions()}));item.appendChild(acts);list.appendChild(item)}
  if(S.editSubscriptionID){const src=S.editSubscriptionID==='__new__'?{id:'',label:'',enabled:true,default:false,scorecard:cards[0]?.id||'',feed_ids:[],match:{all:true}}:await ZR.Services.Subscriptions.get(S.editSubscriptionID);editor.appendChild(renderSubscriptionEditor(src,feeds,cards,S.editSubscriptionID==='__new__'))}
  else editor.innerHTML=`<div class="zr-placeholder"><h3>${esc(t('native.selectSubscription'))}</h3><p>${esc(t('native.selectSubscriptionHint'))}</p></div>`;
  root.appendChild(await renderFeedLibrary(feeds,subs));
}
function renderSubscriptionEditor(src,feeds,cards,isNew){const draft=clone(src);const wrap=html('div');wrap.className='zr-editor-card';const h=html('h3');h.textContent=isNew?t('native.newSubscription'):t('native.editSubscription',{label:src.label});wrap.appendChild(h);
  const id=input(src.id);id.disabled=!isNew;const label=input(src.label);const enabled=checkbox(src.enabled!==false);const def=checkbox(!!src.default);const score=html('select');for(const c of cards){const o=html('option');o.value=c.id;o.textContent=`${c.label} (${c.id})`;o.selected=c.id===src.scorecard;score.appendChild(o)}
  wrap.append(field(t('native.subscriptionID'),id,t('native.idHint')),field(t('native.label'),label),field(t('native.enabled'),enabled),field(t('native.makeDefault'),def),field(t('native.scorecard'),score));
  const feedBox=html('div');feedBox.className='zr-check-grid';for(const f of feeds){const lab=html('label');const cb=checkbox((src.feed_ids||[]).includes(f.id));cb.dataset.feedId=f.id;lab.append(cb,document.createTextNode(` ${f.name} (${f.id})`));feedBox.appendChild(lab)}wrap.append(field(t('native.feedSelection'),feedBox));
  const acts=html('div');acts.className='zr-actions';acts.append(action(t('common.save'),async()=>{const data={...draft,id:id.value.trim(),label:label.value.trim(),enabled:enabled.checked,default:def.checked,scorecard:score.value,feed_ids:[...feedBox.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.dataset.feedId),match:draft.match||{all:true}};const saved=isNew?await ZR.Services.Subscriptions.create(data):await ZR.Services.Subscriptions.update(src.id,data);if(def.checked)await ZR.Services.Subscriptions.setDefault(saved.id);S.editSubscriptionID=saved.id;S.subscriptionID=saved.id;toast(t('native.subscriptionSaved'));await renderSubscriptions()}),action(t('common.cancel'),async()=>{S.editSubscriptionID=null;await renderSubscriptions()}));
  if(!isNew){acts.append(action(t('common.duplicate'),async()=>{const nid=prompt(t('native.copySubscriptionID'),`${src.id}_copy`);if(!nid)return;const nl=prompt(t('native.displayName'),`${src.label} Copy`);const x=await ZR.Services.Subscriptions.duplicate(src.id,nid,nl||undefined);S.editSubscriptionID=x.id;toast(t('native.subscriptionDuplicated'));await renderSubscriptions()}),action(t('common.delete'),async()=>{if(!confirm(t('native.deleteSubscriptionConfirm',{label:src.label})))return;await ZR.Services.Subscriptions.remove(src.id);S.editSubscriptionID=null;if(S.subscriptionID===src.id)S.subscriptionID=null;toast(t('native.subscriptionDeleted'));await renderSubscriptions()},'zr-danger-button'))}wrap.appendChild(acts);return wrap}
async function renderFeedLibrary(feeds,subs){const section=html('div');section.className='zr-section';const head=html('div');head.className='zr-page-head';head.innerHTML=`<div><h3>${esc(t('native.feedLibrary'))}</h3><p class="zr-muted">${esc(t('native.feedLibraryDesc'))}</p></div>`;head.appendChild(action(t('native.newFeed'),async()=>{S.editFeedID='__new__';await renderSubscriptions()}));section.appendChild(head);
  if(S.editFeedID){const src=S.editFeedID==='__new__'?{id:'',name:'',type:'rss',url:'',query:'',max_items:100,enabled:true,query_note:''}:await ZR.Services.Feeds.get(S.editFeedID);section.appendChild(renderFeedEditor(src,S.editFeedID==='__new__'))}
  const table=html('div');table.className='zr-feed-list';for(const f of feeds){const used=subs.filter(s=>(s.feed_ids||[]).includes(f.id));const row=html('div');row.className='zr-feed-row';row.innerHTML=`<div><b>${esc(f.name)}</b><div class="zr-meta">${esc(f.id)} · ${esc(f.type)} · max ${f.max_items||100}${f.enabled===false?' · '+esc(t('native.disabled')):''}</div></div><div class="zr-muted">${esc(used.map(x=>x.label).join(', ')||t('native.notUsed'))}</div>`;const a=html('div');a.className='zr-inline-actions';a.append(action(t('common.edit'),async()=>{S.editFeedID=f.id;await renderSubscriptions()}),action(t('common.test'),async()=>{toast(t('native.testingFeed'));const r=await ZR.Services.Feeds.test(f.id);toast(feedRunMessage(r,'native.feedTestResult'),!!r.errors,!!r.errors)}),action(t('common.duplicate'),async()=>{const nid=prompt(t('native.copyFeedID'),`${f.id}_copy`);if(!nid)return;const nn=prompt(t('native.displayName'),`${f.name} Copy`);await ZR.Services.Feeds.duplicate(f.id,nid,nn||undefined);toast(t('native.feedDuplicated'));await renderSubscriptions()}),action(t('common.delete'),async()=>{if(!confirm(t('native.deleteFeedConfirm',{label:f.name})))return;await ZR.Services.Feeds.remove(f.id);toast(t('native.feedDeleted'));await renderSubscriptions()},'zr-danger-button'));row.appendChild(a);table.appendChild(row)}section.appendChild(table);return section}
function renderFeedEditor(src,isNew){
  const wrap=html('div');wrap.className='zr-editor-card';
  const id=input(src.id);id.disabled=!isNew;
  const name=input(src.name),type=html('select'),url=input(src.url),query=textarea(src.query||'',4),max=input(src.max_items||100,'number');
  const mode=ZR.Feeds.feedMode(src.type);
  for(const [value,key] of [['rss','native.feedTypeRSS'],['link','native.feedTypeLink'],['json_feed','native.feedTypeJSON'],['europe_pmc_api','native.feedTypeEuropePMC']]){
    const option=html('option');option.value=value;option.textContent=t(key);type.appendChild(option);
  }
  type.value=mode;
  max.min=1;max.max=1000;
  const enabled=checkbox(src.enabled!==false),note=textarea(src.query_note||'',2);
  const urlField=field(t('native.feedURL'),url),queryField=field(t('native.feedQuery'),query,t('native.feedQueryHint'));
  const updateMode=()=>{
    const epmc=type.value==='europe_pmc_api';
    queryField.hidden=!epmc;
    urlField.querySelector('small')?.remove();
    const hint=html('small');hint.className='zr-muted';hint.textContent=t(epmc?'native.feedURLHintEuropePMC':type.value==='link'?'native.feedURLHintLink':type.value==='json_feed'?'native.feedURLHintJSON':'native.feedURLHintRSS');urlField.appendChild(hint);
    if(epmc&&!url.value.trim())url.value='https://www.ebi.ac.uk/europepmc/webservices/rest/search';
  };
  type.addEventListener('change',updateMode);
  wrap.append(field(t('native.feedID'),id,t('native.idHint')),field(t('native.feedName'),name),field(t('native.feedType'),type),urlField,queryField,field(t('native.maxItems'),max),field(t('native.enabled'),enabled),field(t('native.feedNote'),note));
  updateMode();
  const a=html('div');a.className='zr-actions';
  a.append(action(t('common.save'),async()=>{const data={id:id.value.trim(),name:name.value.trim(),type:type.value,url:url.value.trim(),query:type.value==='europe_pmc_api'?query.value:'',max_items:Number(max.value),enabled:enabled.checked,query_note:note.value};const saved=isNew?await ZR.Services.Feeds.create(data):await ZR.Services.Feeds.update(src.id,data);S.editFeedID=saved.id;toast(t('native.feedSaved'));await renderSubscriptions()}),action(t('common.cancel'),async()=>{S.editFeedID=null;await renderSubscriptions()}));
  wrap.appendChild(a);return wrap;
}

async function renderScorecards(){
  const root=q('zr-page-scorecards');root.innerHTML=`<div class="zr-empty">${esc(t('common.loading'))}</div>`;const cards=await ZR.Services.Scorecards.list({includeDisabled:true});root.textContent='';
  const head=html('div');head.className='zr-page-head';head.innerHTML=`<div><h2>${esc(t('native.scorecardsTitle'))}</h2><p class="zr-muted">${esc(t('native.scorecardsDesc'))}</p></div>`;head.appendChild(action(t('native.newScorecard'),async()=>{const id=prompt(t('native.newScorecardID'),'new_scorecard');if(!id)return;const label=prompt(t('native.displayName'),id);await ZR.Services.Scorecards.createTemplate(id,label||id);S.editScorecardID=id;S.scorecardDraft=null;toast(t('native.scorecardCreated'));await renderScorecards()}));root.appendChild(head);
  const layout=html('div');layout.className='zr-manager-grid';const list=html('div');list.className='zr-manager-list';const editor=html('div');editor.className='zr-manager-editor';layout.append(list,editor);root.appendChild(layout);
  for(const m of cards){const item=html('div');item.className='zr-manager-item'+(S.editScorecardID===m.id?' selected':'');const tags=[m.bundled?t('native.bundled'):t('native.userDefined'),m.overridden?t('native.override'):null,m.disabled?t('native.disabled'):null].filter(Boolean);item.innerHTML=`<div><b>${esc(m.label)}</b> <span class="zr-badge">v${esc(m.version)}</span></div><small>${esc(m.id)} · ${esc(tags.join(' · '))}</small>`;item.addEventListener('click',async()=>{S.editScorecardID=m.id;S.scorecardDraft=null;S.scorecardJSON=false;await renderScorecards()});list.appendChild(item)}
  if(!S.editScorecardID&&cards.length)S.editScorecardID=cards.find(x=>!x.disabled)?.id||cards[0].id;
  if(S.editScorecardID){try{const pack=await ZR.Services.Scorecards.get(S.editScorecardID);if(!S.scorecardDraft||S.scorecardDraft.id!==pack.card.id)S.scorecardDraft=clone(pack.card);editor.appendChild(await renderScorecardEditor(pack))}catch(e){S.editScorecardID=null;S.scorecardDraft=null;editor.textContent=ZR.I18n.error(e)}}
}
function bindText(control,obj,key,parser=v=>v){control.addEventListener('input',()=>{obj[key]=parser(control.value)});return control}
function renderStringListField(label,obj,key,rows=4){const ta=textarea(linesText(obj[key]),rows);ta.addEventListener('input',()=>{obj[key]=lines(ta.value)});return field(label,ta,t('native.onePerLine'))}
function ensureCardShape(c){c.scope=c.scope||{};c.scope.direct=c.scope.direct||{description:'',anchors:[],aliases:[]};c.scope.contextual=c.scope.contextual||{description:'',anchors:[],aliases:[]};c.scope.transferable=c.scope.transferable||{description:'',topics:[]};c.scope.exclusions=c.scope.exclusions||{description:'',examples:[]};c.semantic_profile=c.semantic_profile||{positive_descriptions:[],negative_descriptions:[],transferable_descriptions:[]};c.topics=c.topics||[];return c}
async function renderScorecardEditor(pack){const meta=pack.meta,c=ensureCardShape(S.scorecardDraft);const wrap=html('div');wrap.className='zr-editor-card';const deps=await ZR.Services.Scorecards.deps(c.id);const top=html('div');top.className='zr-page-head';top.innerHTML=`<div><h3>${esc(c.label)}</h3><p class="zr-muted">${esc(c.id)} · ${esc(meta.bundled?t('native.bundled'):t('native.userDefined'))}${meta.overridden?' · '+esc(t('native.override')):''}${meta.disabled?' · '+esc(t('native.disabled')):''}</p></div>`;const mode=action(S.scorecardJSON?t('native.formEditor'):t('native.advancedJSON'),async()=>{S.scorecardJSON=!S.scorecardJSON;await renderScorecards()});top.appendChild(mode);wrap.appendChild(top);
  if(deps.length){const dep=html('div');dep.className='zr-warning';dep.textContent=t('native.scorecardDependencies',{list:deps.map(x=>x.label||x.id).join(', ')});wrap.appendChild(dep)}
  if(S.scorecardJSON){const ta=textarea(JSON.stringify(c,null,2),28);ta.className='zr-json-editor';wrap.appendChild(ta);wrap.appendChild(action(t('native.applyJSON'),async()=>{const parsed=JSON.parse(ta.value);ZR.Services.Scorecards.validate(parsed);S.scorecardDraft=parsed;S.scorecardJSON=false;await renderScorecards()}));}
  else wrap.appendChild(renderScorecardForm(c));
  const acts=html('div');acts.className='zr-actions';acts.append(action(t('common.save'),async()=>{ZR.Services.Scorecards.validate(c);await ZR.Services.Scorecards.update(c.id,clone(c));S.scorecardDraft=null;toast(t('native.scorecardSaved'));await renderScorecards()}),action(t('common.duplicate'),async()=>{const nid=prompt(t('native.copyScorecardID'),`${c.id}_copy`);if(!nid)return;const nl=prompt(t('native.displayName'),`${c.label} Copy`);await ZR.Services.Scorecards.duplicate(c.id,nid,nl||undefined);S.editScorecardID=nid;S.scorecardDraft=null;toast(t('native.scorecardDuplicated'));await renderScorecards()}));
  if(meta.bundled){if(meta.disabled)acts.append(action(t('native.restoreBundled'),async()=>{await ZR.Services.Scorecards.restore(c.id);S.scorecardDraft=null;toast(t('native.scorecardRestored'));await renderScorecards()}));else{if(meta.overridden)acts.append(action(t('native.resetBundled'),async()=>{if(!confirm(t('native.resetScorecardConfirm',{label:c.label})))return;await ZR.Services.Scorecards.reset(c.id);S.scorecardDraft=null;toast(t('native.scorecardReset'));await renderScorecards()}));acts.append(action(t('native.disableScorecard'),async()=>{if(!confirm(t('native.disableScorecardConfirm',{label:c.label})))return;await ZR.Services.Scorecards.remove(c.id);S.scorecardDraft=null;toast(t('native.scorecardDisabled'));await renderScorecards()},'zr-danger-button'))}}else acts.append(action(t('common.delete'),async()=>{if(!confirm(t('native.deleteScorecardConfirm',{label:c.label})))return;await ZR.Services.Scorecards.remove(c.id);S.editScorecardID=null;S.scorecardDraft=null;toast(t('native.scorecardDeleted'));await renderScorecards()},'zr-danger-button'));wrap.appendChild(acts);return wrap}
function renderScorecardForm(c){const form=html('div');form.className='zr-form';const id=input(c.id);id.disabled=true;const label=bindText(input(c.label),c,'label');const version=input(c.version||1,'number');version.min=1;version.addEventListener('input',()=>c.version=Math.max(1,Number(version.value)||1));const desc=bindText(textarea(c.description,4),c,'description');form.append(field(t('native.scorecardID'),id),field(t('native.label'),label),field(t('native.version'),version),field(t('native.description'),desc));
  form.appendChild(scorecardBranch(t('native.directScope'),c.scope.direct));form.appendChild(scorecardBranch(t('native.contextualScope'),c.scope.contextual));
  const tr=html('fieldset');tr.innerHTML=`<legend>${esc(t('native.transferableScope'))}</legend>`;tr.append(field(t('native.description'),bindText(textarea(c.scope.transferable.description,3),c.scope.transferable,'description')));tr.append(renderTopicCollection(c.scope.transferable.topics,t('native.transferableTopics'),true));form.appendChild(tr);
  form.append(renderTopicCollection(c.topics,t('native.topics'),false));
  const ex=html('fieldset');ex.innerHTML=`<legend>${esc(t('native.exclusions'))}</legend>`;ex.append(field(t('native.description'),bindText(textarea(c.scope.exclusions.description,3),c.scope.exclusions,'description')),renderStringListField(t('native.examples'),c.scope.exclusions,'examples'));form.appendChild(ex);
  const sem=html('fieldset');sem.innerHTML=`<legend>${esc(t('native.semanticProfile'))}</legend>`;sem.append(renderStringListField(t('native.positiveDescriptions'),c.semantic_profile,'positive_descriptions'),renderStringListField(t('native.negativeDescriptions'),c.semantic_profile,'negative_descriptions'),renderStringListField(t('native.transferableDescriptions'),c.semantic_profile,'transferable_descriptions'));form.appendChild(sem);return form}
function scorecardBranch(label,obj){const fs=html('fieldset');fs.innerHTML=`<legend>${esc(label)}</legend>`;fs.append(field(t('native.description'),bindText(textarea(obj.description,3),obj,'description')),renderStringListField(t('native.anchors'),obj,'anchors'),renderStringListField(t('native.aliases'),obj,'aliases'));return fs}
function renderTopicCollection(arr,label,transfer){const fs=html('fieldset');fs.className='zr-topic-collection';fs.innerHTML=`<legend>${esc(label)}</legend>`;arr.forEach((topic,i)=>{const box=html('div');box.className='zr-topic-editor';const id=bindText(input(topic.id),topic,'id'),lab=bindText(input(topic.label),topic,'label'),desc=bindText(textarea(topic.description,2),topic,'description');box.append(field(t('native.topicID'),id),field(t('native.label'),lab),field(t('native.description'),desc),renderStringListField(t('native.anchors'),topic,'anchors',3),renderStringListField(t('native.aliases'),topic,'aliases',3),action(t('common.remove'),async()=>{arr.splice(i,1);await renderScorecards()},'zr-danger-button'));fs.appendChild(box)});fs.appendChild(action(transfer?t('native.addTransferableTopic'):t('native.addTopic'),async()=>{let base=transfer?'transfer_topic':'topic',n=1,id=base;const ids=new Set(arr.map(x=>x.id));while(ids.has(id))id=`${base}_${++n}`;arr.push({id,label:id,description:'',anchors:[],aliases:[]});await renderScorecards()}));return fs}

function feedbackEditor(p,after=()=>renderCurrent()){
  const box=html('div');box.className='zr-editor-card';const model=p.model_judgement||{};
  const title=html('h3');title.textContent=t('native.correctJudgement');box.appendChild(title);
  const scope=selectFilter(['DIRECT','CONTEXTUAL','TRANSFERABLE','OUT_OF_SCOPE'].map(x=>[x,scopeLabel(x)]),p.corrected_scope||p.scope||model.scope||'DIRECT',()=>sync());
  const strength=selectFilter(['HIGH','MEDIUM','LOW'].map(x=>[x,strengthLabel(x)]),p.corrected_strength||p.strength||model.strength||'MEDIUM',()=>{});
  const transfer=input(p.corrected_transferable_topic||p.transferable_topic||'');const note=textarea(p.note||'',2);
  function sync(){strength.disabled=scope.value==='OUT_OF_SCOPE';transfer.disabled=scope.value!=='TRANSFERABLE'}sync();
  box.append(field(t('native.relation'),scope),field(t('native.strength'),strength),field(t('native.transferTopic'),transfer),field(t('native.feedbackNote'),note));
  const save=async(correct)=>{const s=correct?(model.scope||p.scope):scope.value;const st=correct?(model.strength||p.strength):strength.value;await ZR.Services.Feedback.add({paper_id:p.paper_id,scorecard_id:p.scorecard_id,corrected_scope:s,corrected_strength:['OUT_OF_SCOPE','UNCERTAIN'].includes(s)?null:st,corrected_transferable_topic:s==='TRANSFERABLE'?(correct?model.transferable_topic:transfer.value.trim()):null,note:correct?t('native.confirmedNote'):note.value,confirm_correct:correct});toast(t('native.feedbackSaved'));await after()};
  const acts=html('div');acts.className='zr-actions';acts.append(action(t('native.confirmCorrect'),()=>save(true)),action(t('native.saveCorrection'),()=>save(false)));box.appendChild(acts);return box;
}
async function renderFeedback(){
  const root=q('zr-page-feedback');root.innerHTML=`<div class="zr-empty">${esc(t('common.loading'))}</div>`;const {sub}=await resolveSubscription();root.textContent='';if(!sub){root.textContent=t('native.noSubscriptions');return}
  const [profile,recent]=await Promise.all([ZR.Services.Feedback.status(sub.scorecard),ZR.Services.Feedback.recent(sub.scorecard,100)]);
  const head=html('div');head.className='zr-page-head';head.innerHTML=`<div><h2>${esc(t('native.feedbackTitle'))}</h2><p class="zr-muted">${esc(sub.label)} · ${esc(sub.scorecard)}</p></div>`;head.append(action(t('native.rebuildProfile'),async()=>{await ZR.Services.Feedback.rebuild(sub.scorecard);toast(t('native.profileRebuilt'));await renderFeedback()}));root.appendChild(head);
  const state=profile.state||{},counts=profile.counts||{};const stats=html('div');stats.className='zr-section';stats.innerHTML=`<h3>${esc(t('native.profileMaturity'))}</h3><p>${esc(t('native.activeVersion'))}: ${state.active_version??'—'} · ${esc(t('native.pendingRebuild'))}: ${state.pending_rebuild?t('common.yes'):t('common.no')}</p><p>${esc(t('native.total'))}: ${counts.total||0} · ${esc(t('native.positive'))}: ${counts.positive||0} · ${esc(t('native.negative'))}: ${counts.negative||0} · ${esc(t('native.transferable'))}: ${counts.transferable||0}</p><p class="zr-muted">${esc(t('native.profileManualOnly'))}</p>`;root.appendChild(stats);
  const versions=html('div');versions.className='zr-section';versions.innerHTML=`<h3>${esc(t('native.profileVersions'))}</h3>`;for(const v of profile.versions||[]){const row=html('div');row.className='zr-feed-row';row.innerHTML=`<div>v${Number(v.version)} · ${esc(v.built_at||'')}</div><div>${Number(v.positive_count||0)} / ${Number(v.negative_count||0)} / ${Number(v.transferable_count||0)}</div>`;if(Number(v.version)!==Number(state.active_version))row.appendChild(action(t('native.rollback'),async()=>{if(!confirm(t('native.rollbackConfirm',{version:v.version})))return;await ZR.Services.Feedback.rollback(sub.scorecard,v.version);await renderFeedback()}));versions.appendChild(row)}root.appendChild(versions);
  const history=html('div');history.className='zr-section';history.innerHTML=`<h3>${esc(t('native.recentFeedback'))}</h3>`;for(const f of recent){const row=html('div');row.className='zr-feed-row';row.innerHTML=`<div><b>${esc(f.paper_title||('#'+Number(f.paper_id)))}</b> · ${esc(f.corrected_scope||'')} ${esc(f.corrected_strength||'')}<div class="zr-meta">${esc(f.note||'')} · ${esc(f.created_at||'')}</div></div><div>${f.active?t('native.active'):t('native.revoked')}</div>`;const acts=html('div');acts.className='zr-inline-actions';if(f.active){acts.append(action(t('common.edit'),async()=>{S.editFeedbackID=Number(f.id);await renderFeedback()}),action(t('native.revoke'),async()=>{if(!confirm(t('native.revokeConfirm')))return;await ZR.Services.Feedback.revoke(f.id);S.editFeedbackID=null;await renderFeedback()},'zr-danger-button'))}row.appendChild(acts);history.appendChild(row);if(S.editFeedbackID===Number(f.id)){const p={...f,scope:f.corrected_scope||f.model_scope,strength:f.corrected_strength||f.model_strength,model_judgement:{scope:f.model_scope,strength:f.model_strength}};history.appendChild(feedbackEditor(p,async()=>{S.editFeedbackID=null;await renderFeedback()}))}}root.appendChild(history);
}
async function renderSystem(){
  const root=q('zr-page-system');root.innerHTML=`<div class="zr-empty">${esc(t('common.loading'))}</div>`;const s=await ZR.Services.System.status();root.textContent='';
  const section=html('div');section.className='zr-section';section.innerHTML=`<h2>${esc(t('native.systemTitle'))}</h2>`;
  const backend=s.model||s.ollama||{},modelStatus=()=>`${backend.model||'—'} · ${backend.ok?t('native.available'):t('native.unreachable')}`;
  const entries=[[t('native.zotradar'),`${s.plugin.version} · ${s.plugin.ready?t('native.ready'):t('native.notReady')}`],[t('native.zotero'),`${s.zotero.version} · ${s.zotero.platform} · ${s.zotero.locale}`],[t('native.modelProvider'),backend.ok?`${backend.providerLabel||backend.provider||'—'} · ${t('native.available')}`:String(backend.error||t('native.unreachable'))],[t('native.qwen'),modelStatus()],[t('native.easyScholar'),s.settings_meta?.easyScholarKeyConfigured?t('common.configured'):t('common.notConfigured')],[t('native.database'),`${s.database} · ${s.counts.papers} / ${s.counts.screenings} / ${s.counts.feedback}`],[t('native.api'),s.api?.registered?t('native.available'):t('native.unreachable')],[t('native.diagnostics'),`${s.startup?.stage||'—'} ${s.startup?.error||''}`]];
  for(const [label,value] of entries){const row=html('div');row.className='zr-feed-row';row.innerHTML=`<b>${esc(label)}</b><span class="zr-system-value">${esc(value)}</span>`;section.appendChild(row)}root.appendChild(section);
  const logs=html('div');logs.className='zr-section';logs.innerHTML=`<h3>${esc(t('native.logs'))}</h3><pre>${esc((s.logs||[]).join('\n')||t('native.noLogs'))}</pre>`;root.appendChild(logs);
  const migration=html('div');migration.className='zr-section';migration.innerHTML=`<h3>${esc(t('native.migrationTitle'))}</h3><p class="zr-muted">${esc(t('native.migrationDesc'))}</p>`;const path=input('');path.placeholder=t('native.migrationPath');migration.appendChild(field(t('native.migrationPath'),path));const report=html('pre');report.className='zr-migration-report';const acts=html('div');acts.className='zr-actions';acts.append(action(t('native.inspectMigration'),async()=>{const r=await ZR.Services.System.inspectMigration(path.value.trim());report.textContent=JSON.stringify(r,null,2)}),action(t('native.runMigration'),async()=>{if(!confirm(t('native.migrationConfirm')))return;const r=await ZR.Services.System.migrate(path.value.trim());report.textContent=JSON.stringify(r,null,2);toast(t('native.migrationDone'))}));migration.append(acts,report);root.appendChild(migration);
}

function applyWindowState(){try{const w=Number(ZR.Utils.getPref('dashboardWidth',1260)),h=Number(ZR.Utils.getPref('dashboardHeight',820)),x=Number(ZR.Utils.getPref('dashboardX',-1)),y=Number(ZR.Utils.getPref('dashboardY',-1));if(w>=720&&h>=520)window.resizeTo(w,h);if(x>=0&&y>=0)window.moveTo(x,y)}catch(_){}}
function saveWindowState(){try{if(window.outerWidth>=720)ZR.Utils.setPref('dashboardWidth',Math.round(window.outerWidth));if(window.outerHeight>=520)ZR.Utils.setPref('dashboardHeight',Math.round(window.outerHeight));if(window.screenX>=0)ZR.Utils.setPref('dashboardX',Math.round(window.screenX));if(window.screenY>=0)ZR.Utils.setPref('dashboardY',Math.round(window.screenY));ZR.Utils.setPref('dashboardPage',S.page);if(S.subscriptionID)ZR.Utils.setPref('dashboardSubscription',S.subscriptionID)}catch(_){}}
function bindEvents(){for(const u of S.unsubs)try{u()}catch(_){}S.unsubs=[];if(!ZR.Events)return;const refresh=(page)=>{if(S.page===page)renderCurrent().catch(showDashboardError)};S.unsubs.push(ZR.Events.on('papers:changed',()=>refresh('papers')));S.unsubs.push(ZR.Events.on('feedback:changed',e=>{if(S.page==='feedback')refresh('feedback');if(e?.snapshotOnly)return;if(S.page==='papers'&&(!e?.paperID||q('zr-page-papers').querySelector(`[data-paper-id="${Number(e.paperID)}"]`)))refresh('papers')}));S.unsubs.push(ZR.Events.on('subscriptions:default-changed',e=>{if(e?.subscriptionID)S.subscriptionID=e.subscriptionID;if(['papers','feedback'].includes(S.page))renderCurrent().catch(showDashboardError)}));S.unsubs.push(ZR.Events.on('subscriptions:changed',()=>{if(['papers','subscriptions','feedback'].includes(S.page))renderCurrent().catch(showDashboardError)}));S.unsubs.push(ZR.Events.on('feeds:changed',()=>refresh('subscriptions')));S.unsubs.push(ZR.Events.on('scorecards:changed',()=>{if(['papers','subscriptions','scorecards','feedback'].includes(S.page))renderCurrent().catch(showDashboardError)}))}
function bindDisplayEvents(){if(!ZR.Events)return;S.unsubs.push(ZR.Events.on('papers:title-translated',e=>{const line=q('zr-page-papers')?.querySelector(`[data-paper-id="${Number(e.paperID)}"] .zr-title-zh`);if(line)line.textContent=e.title_zh||''}));S.unsubs.push(ZR.Events.on('papers:title-translation-failed',e=>{const line=q('zr-page-papers')?.querySelector(`[data-paper-id="${Number(e.paperID)}"] .zr-title-zh`);if(line)line.textContent=t('native.translationUnavailable')}));S.unsubs.push(ZR.Events.on('journals:display-changed',e=>{for(const card of q('zr-page-papers')?.querySelectorAll('.zr-card')||[]){if(card.dataset.journalKey!==e.key)continue;const name=card.querySelector('.zr-journal-name')?.textContent||'';card.querySelector('.zr-journal').innerHTML=journalMarkup({journal:name,journal_metric:e.metric})}if(S.filters.sort==='if_desc'&&S.page==='papers'){clearTimeout(bindDisplayEvents._timer);bindDisplayEvents._timer=setTimeout(()=>renderPapers().catch(showDashboardError),500)}}));S.unsubs.push(ZR.Events.on('settings:changed',e=>{if(S.page==='papers'&&(e?.keys||[]).some(k=>['showChineseTitle','showScopeColumn','showTopicColumn','priorityAuthors','titleLinkTarget'].includes(k)))renderPapers().catch(showDashboardError)}))}
window.ZotRadarDashboard={navigate:(page,opts={})=>navigate(page,opts)};
async function initializeDashboard(){
  if(!ZR)throw new Error('ZotRadar core unavailable');
  await ensureDashboardStyles();
  applyWindowState();
  q('zr-app').dataset.style='multicolor';
  const init=CTX.initial||{};
  S.subscriptionID=init.subscriptionID||ZR.Utils.getPref('dashboardSubscription','')||null;
  S.selectedPaperID=init.paperID?Number(init.paperID):null;
  S.page=init.page||ZR.Utils.getPref('dashboardPage','papers')||'papers';
  q('zr-subtitle').textContent=`v${ZR.version} · ${ZR.I18n.locale()}`;
  const labels={papers:'native.tab.papers',subscriptions:'native.tab.subscriptions',scorecards:'native.tab.scorecards',feedback:'native.tab.feedback',system:'native.tab.system'};
  document.querySelectorAll('#zr-nav button').forEach(b=>{b.textContent=t(labels[b.dataset.page]);b.addEventListener('click',()=>navigate(b.dataset.page).catch(showDashboardError))});
  q('zr-refresh').title=t('common.refresh');q('zr-close').title=t('common.close');
  q('zr-refresh').addEventListener('click',()=>renderCurrent().catch(showDashboardError));
  q('zr-close').addEventListener('click',()=>window.close());
  bindEvents();bindDisplayEvents();
  await navigate(S.page,init);
}
function showDashboardError(error){
  q('zr-page-papers')?.classList.remove('zr-filter-pending');q('zr-page-papers')?.removeAttribute('aria-busy');
  const name=String(error?.name||'Error'),detail=String(error?.message||error),stack=String(error?.stack||'');
  const message=`${name}: ${detail}${stack?'\n'+stack:''}`;
  const root=q('zr-page-'+S.page)||q('zr-app');
  if(root){root.querySelector('.zr-inline-error')?.remove();const pre=html('pre');pre.className='zr-inline-error zr-danger';pre.style.whiteSpace='pre-wrap';pre.textContent='ZotRadar dashboard error\n'+message;root.prepend(pre)}
  try{Zotero?.logError?.(error)}catch(_){}
}
window.addEventListener('load',()=>{initializeDashboard().catch(showDashboardError)},{once:true});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&S.selectedPaperID){S.selectedPaperID=null;q('zr-page-papers')?.querySelectorAll('.zr-detail-row').forEach(el=>el.remove());e.preventDefault()}});
window.addEventListener('unload',()=>{saveWindowState();for(const u of S.unsubs)try{u()}catch(_){};try{if(ZR.UI&&ZR.UI.dashboardWindow===window)ZR.UI.dashboardWindow=null}catch(_){}});
})();
