(function (ZR) {
  'use strict';
  const registered=[];
  function replyJSON(status,obj){return[status,'application/json; charset=utf-8',JSON.stringify(obj)];}
  async function resource(path){return await ZR.Utils.readResourceText(path);}
  function tokenOK(token){return !!token && String(token)===String(ZR.UI.ensureToken());}
  function queryFromRequest(request){if(request==null)return{};if(request.searchParams&&typeof request.searchParams.forEach==='function'){const out={};request.searchParams.forEach((value,key)=>out[key]=value);return out}if(typeof request==='string')return ZR.Utils.parseQueryString(request);if(typeof request!=='object')return{};for(const k of ['query','queryString','search'])if(typeof request[k]==='string')return ZR.Utils.parseQueryString(request[k]);for(const k of ['url','href','requestURI'])if(typeof request[k]==='string'){try{const u=new URL(request[k],'http://127.0.0.1:23119');const out={};u.searchParams.forEach((v,key)=>out[key]=v);return out}catch(_){}}return{};}
  function bodyFromRequest(request){if(request==null)return{};const data=Object.prototype.hasOwnProperty.call(request,'data')?request.data:request;if(data==null)return{};if(typeof data==='string')return ZR.Utils.safeJSON(data,{})||{};if(typeof data!=='object'||Array.isArray(data))return{};for(const k of ['body','postData']){const v=data[k];if(typeof v==='string'){const p=ZR.Utils.safeJSON(v,null);if(p&&typeof p==='object')return p}else if(v&&typeof v==='object'&&!Array.isArray(v))return v}return data;}
  function endpoint(path,methods,handler,{unsafe=true,contentType='application/json; charset=utf-8'}={}){const C=function(){};C.prototype={supportedMethods:methods,allowRequestsFromUnsafeWebContent:unsafe,init:async function(request){try{const result=await handler(request);if(result&&result.__raw)return[result.status||200,result.type||contentType,result.body||''];return replyJSON(200,result==null?{ok:true}:result)}catch(e){Zotero.logError(e);const msg=String(e&&e.message||e);return replyJSON(msg==='FORBIDDEN'?403:400,{ok:false,error:ZR.I18n.error(e)})}}};Zotero.Server.Endpoints[path]=C;registered.push(path)}
  async function status(){const sys=await ZR.Services.System.status(),scorecards=await ZR.Services.Scorecards.list({includeDisabled:true}),subscriptions=await ZR.Services.Subscriptions.list(),profiles={};for(const c of scorecards.filter(x=>!x.disabled))profiles[c.id]=await ZR.Services.Feedback.status(c.id);return{ok:true,...sys,scorecards,subscriptions,profiles,settings_schema:ZR.Settings.publicSchema()};}
  async function paperPayload(subscriptionID,opts={}){const subs=await ZR.Services.Subscriptions.list(),sub=subscriptionID?subs.find(x=>x.id===String(subscriptionID)):subs.find(x=>x.default&&x.enabled!==false)||subs.find(x=>x.enabled!==false);if(!sub)throw new Error(subscriptionID?'Unknown subscription: '+subscriptionID:'No active subscriptions');const card=(await ZR.Services.Scorecards.get(sub.scorecard)).card,r=await ZR.Services.Papers.list({subscriptionID:sub.id,limit:10000,includeFeedback:true,imported:opts.imported||'all'});return{subscription:sub,scorecard:{id:card.id,label:card.label,version:card.version,description:card.description,topics:card.topics||[],transferable_topics:card.scope.transferable.topics||[]},rows:r.rows,total:r.total};}
  async function init(){
    // Legacy/developer browser UI retained for compatibility. Zotero Native Dashboard is primary.
    endpoint('/zotradar/',['GET'],async()=>{const token=ZR.UI.ensureToken();let html=await resource('web/index.html');html=html.replace('__ZR_TOKEN__',ZR.Utils.escapeHTML(token));return{__raw:true,type:'text/html; charset=utf-8',body:html}});
    endpoint('/zotradar/app.js',['GET'],async()=>({__raw:true,type:'application/javascript; charset=utf-8',body:await resource('web/app.js')}));
    endpoint('/zotradar/style.css',['GET'],async()=>({__raw:true,type:'text/css; charset=utf-8',body:await resource('web/style.css')}));
    endpoint('/zotradar/api/ping',['GET'],async()=>({ok:true,plugin:'ZotRadar',version:ZR.version,ready:!!ZR.started,locale:ZR.I18n.locale(),primary_ui:'zotero-native'}));
    endpoint('/zotradar/api/i18n',['GET'],async()=>({ok:true,...ZR.I18n.bundle()}));
    endpoint('/zotradar/api/status',['GET'],async()=>status());
    endpoint('/zotradar/api/papers',['GET'],async d=>{const q=queryFromRequest(d);return paperPayload(q.subscription||null,{imported:q.imported||'all'})});
    endpoint('/zotradar/api/subscriptions',['GET'],async()=>({ok:true,subscriptions:await ZR.Services.Subscriptions.list(),counts:await ZR.Services.Subscriptions.counts()}));
    endpoint('/zotradar/api/scorecards',['GET'],async()=>({ok:true,scorecards:await ZR.Services.Scorecards.list({includeDisabled:true})}));
    endpoint('/zotradar/api/scorecard',['GET'],async d=>{const q=queryFromRequest(d),id=q.id||ZR.Utils.getPref('defaultScorecard','protein_design');return{ok:true,...await ZR.Services.Scorecards.get(id)}});
    endpoint('/zotradar/api/feedback',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,...await ZR.Services.Feedback.add(p)}});
    endpoint('/zotradar/api/feedback/recent',['GET'],async d=>{const q=queryFromRequest(d);return{ok:true,rows:await ZR.Services.Feedback.recent(String(q.scorecard_id||''),Math.min(100,Math.max(1,Number(q.limit||50))))}});
    endpoint('/zotradar/api/feedback/revoke',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:await ZR.Services.Feedback.revoke(Number(p.feedback_id))}});
    endpoint('/zotradar/api/profile/rebuild',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,profile:await ZR.Services.Feedback.rebuild(String(p.scorecard_id||''))}});
    endpoint('/zotradar/api/profile/rollback',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:await ZR.Services.Feedback.rollback(String(p.scorecard_id||''),Number(p.version))}});
    endpoint('/zotradar/api/run',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return await ZR.Services.Subscriptions.run(String(p.subscription_id||ZR.Settings.get('defaultSubscription')))});
    endpoint('/zotradar/api/import',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');const item=await ZR.Services.Papers.importToZotero(Number(p.paper_id));return{ok:true,library_id:item.libraryID,key:item.key,id:item.id}});
    endpoint('/zotradar/api/maintenance/status',['GET'],async()=>({ok:true,job:ZR.Services.Papers.maintenanceStatus()}));
    endpoint('/zotradar/api/maintenance/start',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,job:await ZR.Services.Papers.startMaintenance({mode:p.mode,subscriptionID:p.subscription_id,itemKeys:p.item_keys})}});
    endpoint('/zotradar/api/maintenance/cancel',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,job:ZR.Services.Papers.cancelMaintenance()}});
    endpoint('/zotradar/api/maintenance/purge-notices',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,...await ZR.Services.Papers.purgeCorrectionNotices({apply:p.apply===true})}});
    endpoint('/zotradar/api/subscription/save',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');const r=p.existing_id?await ZR.Services.Subscriptions.update(p.existing_id,p.subscription):await ZR.Services.Subscriptions.create(p.subscription);return{ok:true,subscription:r}});
    endpoint('/zotradar/api/subscription/delete',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,result:await ZR.Services.Subscriptions.remove(p.id)}});
    endpoint('/zotradar/api/scorecard/save',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,...await ZR.Services.Scorecards.update(p.scorecard.id,p.scorecard)}});
    endpoint('/zotradar/api/scorecard/create',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,...await ZR.Services.Scorecards.createTemplate(String(p.id||''),String(p.label||''))}});
    endpoint('/zotradar/api/scorecard/copy',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,...await ZR.Services.Scorecards.duplicate(String(p.source_id||''),String(p.id||''),String(p.label||''))}});
    endpoint('/zotradar/api/scorecard/delete',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,result:await ZR.Services.Scorecards.remove(String(p.id||''))}});
    endpoint('/zotradar/api/scorecard/restore',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,...await ZR.Services.Scorecards.restore(String(p.id||''))}});
    endpoint('/zotradar/api/settings',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');const values={};for(const def of ZR.Settings.SCHEMA)if(Object.prototype.hasOwnProperty.call(p,def.key))values[def.key]=p[def.key];const r=await ZR.Settings.update(values,{preserveBlankSecrets:true,clearSecrets:Array.isArray(p.clearSecrets)?p.clearSecrets:[]});return{ok:true,settings:r.values,settings_meta:r.meta}});
    endpoint('/zotradar/api/easyscholar/test',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return await ZR.Journal.testEasyScholar()});
    endpoint('/zotradar/api/migrate-v4',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,stats:await ZR.Services.System.migrate(String(p.path||''))}});
    endpoint('/zotradar/api/migration/inspect',['POST'],async d=>{const p=bodyFromRequest(d);if(!tokenOK(p.token))throw new Error('FORBIDDEN');return{ok:true,report:await ZR.Services.System.inspectMigration(String(p.path||''))}});
  }
  function shutdown(){for(const p of registered){try{delete Zotero.Server.Endpoints[p]}catch(_){}}registered.length=0}
  ZR.HTTPServer={init,shutdown,status,paperPayload};
})(ZR);
