(()=>{'use strict';
const qs=new URLSearchParams(location.search),metaToken=(document.querySelector('meta[name="zotradar-token"]')||{}).content||'',TOKEN=metaToken||qs.get('token')||'';
const state={status:null,papers:null,scorecard:null,scorecardMeta:null,currentSubscription:null,locale:'en-US',strings:{}};
const $=id=>document.getElementById(id);
const el=(tag,props={},...children)=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(props)){if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else if(v!=null)n.setAttribute(k,v)}for(const c of children){if(c==null)continue;n.append(c.nodeType?c:document.createTextNode(String(c)))}return n};
function fmt(text,vars={}){return String(text==null?'':text).replace(/\{([A-Za-z0-9_]+)\}/g,(_,k)=>vars[k]==null?'':String(vars[k]))}
function t(key,vars={}){return fmt(state.strings[key]??key,vars)}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3000)}
async function api(path,{method='GET',body=null,query={}}={}){if(method==='GET'){const u=new URL('/zotradar/api/'+path,location.origin);Object.entries(query).forEach(([k,v])=>{if(v!=null)u.searchParams.set(k,v)});const r=await fetch(u),text=await r.text();let j;try{j=JSON.parse(text)}catch(_){throw new Error(`GET ${path} returned ${r.status}: ${text.slice(0,240)}`)}if(!r.ok||j.ok===false)throw new Error(j.error||r.statusText);return j}if(!TOKEN)throw new Error('Write access token is missing. Open the dashboard from Zotero → Tools.');const r=await fetch('/zotradar/api/'+path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({token:TOKEN,...(body||{})})}),text=await r.text();let j;try{j=JSON.parse(text)}catch(_){throw new Error(`${method} ${path} returned ${r.status}: ${text.slice(0,240)}`)}if(!r.ok||j.ok===false)throw new Error(j.error||r.statusText);return j}
function badge(text,muted=false){return el('span',{class:'badge'+(muted?' muted':'')},text)}
function setText(id,key){const n=$(id);if(n)n.textContent=t(key)}
function applyStaticI18n(){
  document.documentElement.lang=state.locale;
  const map={compatibilityNotice:'web.compatibilityNotice',appSubtitle:'app.subtitle',healthBadge:'common.connecting',runNow:'web.runNow',tabBtnPapers:'web.tabPapers',tabBtnFeedback:'web.tabFeedback',tabBtnScorecards:'web.tabScorecards',tabBtnSettings:'web.tabSettings',subscriptionLabel:'web.subscription',correctedOnlyLabel:'web.correctedOnly',colGrade:'web.colGrade',colPriority:'web.colPriority',colPaper:'web.colPaper',colScope:'web.colScope',colJournal:'web.colJournal',colDate:'web.colDate',newScorecard:'web.newScorecard',saveScorecard:'web.saveOverride',copyScorecard:'web.copy',deleteScorecard:'web.deleteDisable',restoreScorecard:'web.restoreBundled',scorecardHint:'web.scorecardHint'};
  for(const[id,key]of Object.entries(map))setText(id,key);
  $('search').placeholder=t('web.searchPlaceholder');
  $('gradeFilter').options[0].textContent=t('web.allGrades');
  $('scopeFilter').options[0].textContent=t('web.allScopes');
  $('topicFilter').options[0].textContent=t('web.allTopics');
}
async function loadI18n(){try{const r=await api('i18n');state.locale=r.locale||'en-US';state.strings=r.strings||{};}catch(_){state.locale='en-US';state.strings={};}applyStaticI18n()}
function tab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id==='tab-'+name));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));if(name==='feedback')renderFeedback();if(name==='scorecards')renderScorecards();if(name==='settings')renderSettings()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));

async function loadStatus({preserveSubscription=true}={}){
  const old=preserveSubscription?$('subscriptionSelect').value:'';
  state.status=await api('status');
  if(state.status.locale&&state.status.locale!==state.locale){state.locale=state.status.locale;const b=await api('i18n');state.strings=b.strings||state.strings;applyStaticI18n();}
  {const model=state.status.model||state.status.ollama||{};$('healthBadge').textContent=model.ok?`${model.providerLabel||model.provider||'Model'} ✓`:'Model unavailable';$('healthBadge').className='badge '+(model.ok?'':'muted');}
  const sel=$('subscriptionSelect');sel.textContent='';for(const s of state.status.subscriptions||[]){sel.append(el('option',{value:s.id},`${s.label} · ${s.scorecard}`))}
  if(old&&[...sel.options].some(o=>o.value===old))sel.value=old;else{const d=(state.status.subscriptions||[]).find(x=>x.default);if(d)sel.value=d.id;}
  await loadPapers();
}

async function loadPapers(){
  const sid=$('subscriptionSelect').value;if(!sid){state.papers={rows:[]};renderPapers();$('subscriptionInfo').textContent=t('web.noSubscriptions');return;}
  state.currentSubscription=sid;state.papers=await api('papers',{query:{subscription:sid}});
  const sc=state.papers.scorecard,sub=state.papers.subscription;$('subscriptionInfo').textContent=`${sub.label} → ${t('web.tabScorecards')}: ${sc.label} (${sc.id}) · feeds: ${(sub.feed_ids||[]).join(', ')}`;
  const tf=$('topicFilter'),prev=tf.value;tf.textContent='';tf.append(el('option',{value:''},t('web.allTopics')));for(const x of sc.topics||[])tf.append(el('option',{value:x.id},x.label||x.id));for(const x of sc.transferable_topics||[])tf.append(el('option',{value:'transfer:'+x.id},t('web.transferPrefix')+(x.label||x.id)));if([...tf.options].some(o=>o.value===prev))tf.value=prev;renderPapers();
}
function filteredRows(){if(!state.papers)return[];const q=$('search').value.trim().toLowerCase(),g=$('gradeFilter').value,s=$('scopeFilter').value,topic=$('topicFilter').value,c=$('correctedOnly').checked;return(state.papers.rows||[]).filter(r=>(!q||[r.title,r.abstract,(r.authors||[]).join(' ')].join(' ').toLowerCase().includes(q))&&(!g||r.grade===g)&&(!s||r.scope===s)&&(!topic||(topic.startsWith('transfer:')?r.transferable_topic===topic.slice(9):(r.topics||[]).includes(topic)))&&(!c||r.user_overridden))}
function renderPapers(){const rows=filteredRows(),body=$('paperRows');body.textContent='';$('paperCount').textContent=t('web.items',{count:rows.length});for(const r of rows){const tr=el('tr',{onClick:()=>openPaper(r)});tr.append(el('td',{},el('span',{class:'grade'},r.grade||'—')),el('td',{class:'score'},r.reading_priority==null?'—':Number(r.reading_priority).toFixed(1)),el('td',{},el('div',{class:'title'},r.title),el('div',{class:'subline'},(r.authors||[]).slice(0,3).join(', ')+(r.user_overridden?' · USER CORRECTED':''))),el('td',{},badge(r.scope||'—'),r.strength?document.createTextNode(' '+r.strength):null,(r.topics||[]).length?el('div',{class:'subline'},(r.topics||[]).join(' · ')):null),el('td',{},r.journal||'—'),el('td',{},r.published||'—'),el('td',{},r.zotero_key?badge(t('web.inZotero'),true):el('button',{class:'secondary',onClick:e=>{e.stopPropagation();importPaper(r)}},t('web.import'))));body.append(tr)}}
async function importPaper(r){try{await api('import',{method:'POST',body:{paper_id:r.paper_id}});toast(t('web.imported'));await loadPapers()}catch(e){toast(e.message)}}
function metric(label,value){return el('div',{class:'metric'},el('span',{class:'muted'},label),el('b',{},value==null?'—':value))}
function openPaper(r){const b=$('modalBody');b.textContent='';b.append(el('h2',{},r.title),el('div',{},badge(r.scope),document.createTextNode(' '),r.strength?badge(r.strength,true):null,...(r.topics||[]).map(x=>badge(x,true))),el('div',{class:'metric-grid'},metric('Grade',r.grade),metric('Reading priority',r.reading_priority==null?'—':Number(r.reading_priority).toFixed(1)),metric('Base relevance',r.base_relevance),metric('Feedback',r.feedback_adjustment),metric('Journal adj.',r.journal_adjustment),metric('Profile',r.profile_version||'—')));
  const sec=el('div',{class:'section'},el('h3',{},t('web.reason')),el('p',{},r.reason||'—'));if(r.positive_evidence&&r.positive_evidence.length)sec.append(el('h4',{},t('web.positiveEvidence')),el('ul',{class:'evidence'},...r.positive_evidence.map(x=>el('li',{},x))));if(r.negative_evidence&&r.negative_evidence.length)sec.append(el('h4',{},t('web.negativeEvidence')),el('ul',{class:'evidence'},...r.negative_evidence.map(x=>el('li',{},x))));if(r.uncertainty)sec.append(el('p',{class:'muted'},t('web.uncertainty',{value:r.uncertainty})));b.append(sec,el('div',{class:'section'},el('h3',{},t('web.abstract')),el('p',{},r.abstract||t('web.noAbstract'))));
  const f=el('div',{class:'section'},el('h3',{},t('web.feedback'))),form=el('div',{class:'feedback-form'}),scope=el('select'),strength=el('select');for(const x of ['DIRECT','CONTEXTUAL','TRANSFERABLE','OUT_OF_SCOPE'])scope.append(el('option',{value:x},x));for(const x of ['HIGH','MEDIUM','LOW'])strength.append(el('option',{value:x},x));scope.value=r.feedback&&r.feedback.corrected_scope||r.scope||'DIRECT';strength.value=r.feedback&&r.feedback.corrected_strength||r.strength||'MEDIUM';const transfer=el('select');transfer.append(el('option',{value:''},t('web.unspecifiedTransfer')));for(const x of state.papers.scorecard.transferable_topics||[])transfer.append(el('option',{value:x.id},x.label||x.id));transfer.value=r.feedback&&r.feedback.corrected_transferable_topic||r.transferable_topic||'';const transferLabel=el('label',{},t('web.transferTopic')+' ',transfer);transferLabel.style.display=scope.value==='TRANSFERABLE'?'':'none';scope.addEventListener('change',()=>transferLabel.style.display=scope.value==='TRANSFERABLE'?'':'none');const priority=el('select');for(const x of [['',t('web.priorityNormal')],['TOO_HIGH',t('web.priorityHigh')],['TOO_LOW',t('web.priorityLow')]])priority.append(el('option',{value:x[0]},x[1]));priority.value=r.feedback&&r.feedback.priority_feedback||'';const note=el('textarea',{class:'wide',placeholder:t('web.note')});note.value=r.feedback&&r.feedback.note||'';
  form.append(el('label',{},t('web.relation')+' ',scope),el('label',{},t('web.strength')+' ',strength),transferLabel,el('label',{},t('web.priority')+' ',priority),note,el('button',{onClick:async()=>{try{await api('feedback',{method:'POST',body:{paper_id:r.paper_id,scorecard_id:state.papers.scorecard.id,corrected_scope:scope.value,corrected_strength:['OUT_OF_SCOPE','UNCERTAIN'].includes(scope.value)?null:strength.value,corrected_transferable_topic:transfer.value||null,priority_feedback:priority.value||null,note:note.value}});toast(t('web.feedbackSaved'));$('modal').classList.add('hidden');await loadPapers()}catch(e){toast(e.message)}}},t('web.saveFeedback')));
  if(r.feedback)form.append(el('button',{class:'danger',onClick:async()=>{try{await api('feedback/revoke',{method:'POST',body:{feedback_id:r.feedback.id}});toast(t('web.feedbackRevoked'));$('modal').classList.add('hidden');await loadPapers()}catch(e){toast(e.message)}}},t('web.revokeFeedback')));f.append(form);b.append(f);$('modal').classList.remove('hidden');
}

async function renderFeedback(){if(!state.status)await loadStatus();const p=$('feedbackPanel');p.textContent='';for(const c of (state.status.scorecards||[]).filter(x=>!x.disabled)){const st=state.status.profiles[c.id]||{state:{},versions:[],counts:{}},card=el('div',{class:'card'},el('h3',{},c.label),el('p',{},`${t('web.feedback')} ${st.counts.total||0} · Positive ${st.counts.positive||0} · Negative ${st.counts.negative||0} · Transferable ${st.counts.transferable||0}`),el('p',{class:'muted'},`Profile: ${st.state.active_version?'v'+st.state.active_version:t('web.notBuilt')}${st.state.pending_rebuild?' · '+t('web.pendingRebuild'):''}`));card.append(el('button',{onClick:async()=>{try{await api('profile/rebuild',{method:'POST',body:{scorecard_id:c.id}});toast(t('web.profileRebuilt'));state.status=await api('status');renderFeedback()}catch(e){toast(e.message)}}},t('web.rebuildProfile')));if((st.versions||[]).length){const select=el('select');for(const v of st.versions)select.append(el('option',{value:v.version},`v${v.version} · P${v.positive_count}/N${v.negative_count}/T${v.transferable_count}`));card.append(document.createTextNode(' '+t('web.rollbackTo')),select,el('button',{class:'secondary',onClick:async()=>{try{await api('profile/rollback',{method:'POST',body:{scorecard_id:c.id,version:Number(select.value)}});toast(t('web.profileRolledBack'));state.status=await api('status');renderFeedback()}catch(e){toast(e.message)}}},t('web.rollback')))}p.append(card)}}

async function renderScorecards(preferID=null){state.status=await api('status');const list=$('scorecardList');list.textContent='';for(const c of state.status.scorecards||[]){const label=`${c.disabled?t('web.disabled'):''}${c.label}\n${c.id} · v${c.version}${c.overridden?' · override':''}`;list.append(el('button',{class:c.disabled?'disabled-card':'',onClick:()=>loadScorecard(c.id)},label))}const id=preferID||(state.scorecard&&state.scorecard.id)||(state.status.scorecards[0]||{}).id;if(id)await loadScorecard(id)}
async function loadScorecard(id){try{const r=await api('scorecard',{query:{id}});state.scorecard=r.scorecard;state.scorecardMeta=r.meta||{};$('scorecardEditorTitle').textContent=`${r.scorecard.label} · ${r.scorecard.id}`;$('scorecardMeta').textContent=`${state.scorecardMeta.bundled?'bundled':'user'}${state.scorecardMeta.overridden?' + override':''}${state.scorecardMeta.disabled?' · disabled':''}`;$('scorecardEditor').value=JSON.stringify(r.scorecard,null,2)}catch(e){toast(e.message)}}
async function saveScorecard(){try{const c=JSON.parse($('scorecardEditor').value);await api('scorecard/save',{method:'POST',body:{scorecard:c}});toast(t('web.scorecardSaved'));await renderScorecards(c.id);await loadStatus()}catch(e){toast(t('web.saveFailed',{error:e.message}))}}
async function newScorecard(){const id=prompt(t('web.newScorecardID'));if(!id)return;const label=prompt(t('web.displayName'),id)||id;try{await api('scorecard/create',{method:'POST',body:{id,label}});toast(t('web.created'));await renderScorecards(id);await loadStatus()}catch(e){toast(e.message)}}
async function copyScorecard(){if(!state.scorecard)return;const id=prompt(t('web.copyScorecardID'));if(!id)return;const label=prompt(t('web.displayName'),state.scorecard.label+' Copy')||id;try{await api('scorecard/copy',{method:'POST',body:{source_id:state.scorecard.id,id,label}});toast(t('web.copied'));await renderScorecards(id);await loadStatus()}catch(e){toast(e.message)}}
async function deleteScorecard(){if(!state.scorecard)return;if(!confirm(t('web.deleteConfirm',{label:state.scorecard.label,id:state.scorecard.id})))return;try{await api('scorecard/delete',{method:'POST',body:{id:state.scorecard.id}});toast(t('web.deletedDisabled'));state.scorecard=null;await renderScorecards();await loadStatus()}catch(e){toast(e.message)}}
async function restoreScorecard(){if(!state.scorecard)return;try{await api('scorecard/restore',{method:'POST',body:{id:state.scorecard.id}});toast(t('web.restoredBundled'));await renderScorecards(state.scorecard.id);await loadStatus()}catch(e){toast(e.message)}}

async function renderSettings(){
  state.status=await api('status');const s=state.status.settings||{},meta=state.status.settings_meta||{},schema=state.status.settings_schema||[],p=$('settingsPanel');p.textContent='';
  const groups=[];for(const def of schema){let g=groups.find(x=>x.key===def.group);if(!g){g={key:def.group,defs:[]};groups.push(g)}g.defs.push(def)}const controls=new Map(),clearChecks=new Map();
  for(const g of groups){const card=el('div',{class:'card'},el('h3',{},t('group.'+g.key)));for(const def of g.defs){let input;if(def.type==='boolean'){input=el('input',{type:'checkbox'});input.checked=!!s[def.key];card.append(el('p',{},input,' ',def.label))}else if(def.type==='enum'){input=el('select');for(const c of def.choices||[])input.append(el('option',{value:c.value},c.label));input.value=s[def.key]??def.default;card.append(el('p',{},def.label,' ',input));if(def.key==='reasoningEffort')card.append(el('p',{class:'muted'},t('setting.reasoningHint')))}else if(def.type==='scorecard'||def.type==='subscription'){input=el('select');const choices=def.type==='subscription'?(state.status.subscriptions||[]).filter(x=>x.enabled!==false):(state.status.scorecards||[]).filter(x=>!x.disabled);for(const c of choices)input.append(el('option',{value:c.id},`${c.label} (${c.id})`));input.value=s[def.key]||def.default||'';card.append(el('p',{},def.label,' ',input))}else{input=el('input',{type:def.type==='secret'?'password':def.type==='integer'?'number':'text'});if(def.min!=null)input.min=def.min;if(def.max!=null)input.max=def.max;if(def.step!=null)input.step=def.step;if(def.type==='secret'){input.value='';const configured=!!meta[def.key+'Configured'];input.placeholder=configured?t('secret.savedHint'):(def.placeholder||t('common.optional'));const badgeNode=badge(configured?t('secret.savedBadge'):t('common.notConfigured'),true);const clear=el('input',{type:'checkbox'});clearChecks.set(def.key,clear);card.append(el('p',{},def.label,' ',input,' ',badgeNode,' ',clear,' ',t('secret.clearLabel')))}else{input.value=s[def.key]??def.default??'';card.append(el('p',{},def.label,' ',input))}}controls.set(def.key,{def,input})}p.append(card)}
  const saveCurrent=async({silent=false}={})=>{const body={},clearSecrets=[];for(const[key,{def,input}]of controls){body[key]=def.type==='boolean'?input.checked:def.type==='integer'?Number(input.value):input.value;if(def.type==='secret'&&clearChecks.get(key)?.checked)clearSecrets.push(key)}body.clearSecrets=clearSecrets;const r=await api('settings',{method:'POST',body});state.status.settings_meta={...(state.status.settings_meta||{}),...(r.settings_meta||{})};if(!silent)toast(t('web.settingsSaved'));return r;};
  const actions=el('div',{class:'card'},el('h3',{},t('web.settingsActions')));actions.append(
    el('button',{onClick:async()=>{try{await saveCurrent();await loadStatus();renderSettings()}catch(e){toast(t('web.saveFailed',{error:e.message}))}}},t('web.saveSettings')),
    document.createTextNode(' '),
    el('button',{class:'secondary',onClick:async()=>{try{const r=await api('status'),m=r.model||r.ollama||{};toast(m.ok?`${m.providerLabel||m.provider}: ${m.model}`:`Model unavailable: ${m.error||'unknown'}`)}catch(e){toast(e.message)}}},t('prefs.testModel')),
    document.createTextNode(' '),
    el('button',{class:'secondary',onClick:async()=>{try{await saveCurrent({silent:true});const r=await api('easyscholar/test',{method:'POST'});toast(r.ok?t('web.easyScholarOK',{journal:r.journal}):t('web.easyScholarFailed',{error:r.error||'unknown'}));await loadStatus();renderSettings()}catch(e){toast(t('web.easyScholarFailed',{error:e.message}))}}},t('web.testEasyScholar'))
  );p.append(actions);
  const mig=el('div',{class:'card'},el('h3',{},t('web.migrationTitle')),el('p',{class:'muted'},t('web.migrationDesc')));const mp=el('input',{placeholder:t('web.migrationPlaceholder'),style:'width:100%'});mig.append(mp,el('p',{},el('button',{onClick:async()=>{try{const r=await api('migrate-v4',{method:'POST',body:{path:mp.value.trim()}});toast(t('web.migrationDone',{papers:r.stats.papers,screenings:r.stats.screenings,journals:r.stats.journals}));await loadStatus();renderSettings()}catch(e){toast(t('web.migrationFailed',{error:e.message}))}}},t('web.startMigration'))));
  p.append(mig,el('div',{class:'card'},el('h3',{},t('web.subscriptionsTitle')),el('pre',{},JSON.stringify(state.status.subscriptions||[],null,2))),el('div',{class:'card'},el('h3',{},t('web.systemStatus')),el('pre',{},JSON.stringify({plugin:state.status.plugin,zotero:{...state.status.zotero,locale:state.status.locale},model:state.status.model||state.status.ollama,runInProgress:state.status.run_in_progress,lastDailyRun:meta.lastDailyRun,dataDir:meta.dataDir,database:meta.dbPath,easyScholarConfigured:!!meta.easyScholarKeyConfigured},null,2))));
}

$('runNow').onclick=async()=>{try{$('runNow').disabled=true;const sid=$('subscriptionSelect').value;toast(t('web.running'));const r=await api('run',{method:'POST',body:{subscription_id:sid||null}});toast(t('web.runDone',{fetched:r.fetched,screenings:r.screenings}));await loadPapers()}catch(e){toast(e.message)}finally{$('runNow').disabled=false}};
$('subscriptionSelect').onchange=loadPapers;for(const id of ['search','gradeFilter','scopeFilter','topicFilter','correctedOnly'])$(id).addEventListener(id==='search'?'input':'change',renderPapers);$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};$('saveScorecard').onclick=saveScorecard;$('newScorecard').onclick=newScorecard;$('copyScorecard').onclick=copyScorecard;$('deleteScorecard').onclick=deleteScorecard;$('restoreScorecard').onclick=restoreScorecard;

(async()=>{try{await loadI18n();if(!TOKEN){const b=document.createElement('div');b.style.cssText='padding:8px 14px;background:#fff4ce;border-bottom:1px solid #e0c15a;font:13px system-ui';b.textContent=t('web.readOnly');document.body.prepend(b)}await loadStatus()}catch(e){document.body.innerHTML='<main style="max-width:760px;margin:80px auto;font-family:system-ui"><h1>ZotRadar</h1><h2>'+t('web.startupFailed')+'</h2><pre>'+String(e.message).replace(/[&<>]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[s]))+'</pre><p>'+t('web.startupHint')+'</p></main>'}})();
})();
